using System.Collections.Generic;

namespace Library
{
    public static class Libraries
    {
        public const int ShandaMir2OffSet = 100, WemadeMir3OffSet = 200, ShandaMir3OffSet = 300;
        public static Dictionary<LibraryFile, string> LibraryList = new Dictionary<LibraryFile, string>
        {
            [LibraryFile.Interface1c] = @"Data\Interface1c.Zl",
            [LibraryFile.Interface1cExtended] = @"Data\Interface1c-Extended.Zl",
            [LibraryFile.Interface] = @"Data\Interface.Zl",
            [LibraryFile.GameInter] = @"Data\GameInter.Zl",
            [LibraryFile.Equip] = @"Data\Equip.Zl",
            [LibraryFile.EquipEffect_UI] = @"Data\EquipEffect-UI.Zl",
            [LibraryFile.EquipEffect_Part] = @"Data\EquipEffect-Part.Zl",
            [LibraryFile.EquipEffect_Full] = @"Data\EquipEffect-Full.Zl",
            [LibraryFile.EquipEffect_FullEx1] = @"Data\EquipEffect-FullEx1.Zl",
            [LibraryFile.EquipEffect_FullEx2] = @"Data\EquipEffect-FullEx2.Zl",
            [LibraryFile.EquipEffect_FullEx3] = @"Data\EquipEffect-FullEx3.Zl",
            [LibraryFile.ProgUse] = @"Data\ProgUse.Zl",
            [LibraryFile.StoreItems] = @"Data\StoreItems.Zl",
            [LibraryFile.Inventory] = @"Data\Inventory.Zl",
            [LibraryFile.Ground] = @"Data\Ground.Zl",
            [LibraryFile.NPC] = @"Data\NPC.Zl",
            [LibraryFile.GameInter2] = @"Data\GameInter2.Zl",
            [LibraryFile.MiniMap] = @"Data\MiniMap.Zl",
            [LibraryFile.MiniMap2] = @"Data\MiniMap2.Zl",

            [LibraryFile.CastleFlag] = @"Data\Flag.Zl",

            [LibraryFile.MiniMapIcon] = @"Data\MiniMapIcon.Zl",

            [LibraryFile.Background] = @"Data\Background.Zl",

            [LibraryFile.MagicIcon] = @"Data\MIcon.Zl",
            [LibraryFile.CBIcon] = @"Data\CBIcons.Zl",
            [LibraryFile.QuestIcon] = @"Data\QuestIcons.Zl",

            [LibraryFile.MiniGames] = @"Data\MiniGames.Zl",

            [LibraryFile.NPCImage] = @"Data\NPCface.Zl",
            [LibraryFile.MonImage] = @"Data\MonImg.Zl",

            [LibraryFile.PEquipB1] = @"Data\PEquipB1.Zl",
            [LibraryFile.PEquipH1] = @"Data\PEquipH1.Zl",

            [LibraryFile.M_Hum] = @"Data\M-Hum.Zl",
            [LibraryFile.M_HumEx1] = @"Data\M-HumEx1.Zl",
            [LibraryFile.M_HumEx2] = @"Data\M-HumEx2.Zl",
            [LibraryFile.M_HumEx3] = @"Data\M-HumEx3.Zl",
            [LibraryFile.M_HumEx4] = @"Data\M-HumEx4.Zl",
            [LibraryFile.M_HumEx10] = @"Data\M-HumEx10.Zl",
            [LibraryFile.M_HumEx11] = @"Data\M-HumEx11.Zl",
            [LibraryFile.M_HumEx12] = @"Data\M-HumEx12.Zl",
            [LibraryFile.M_HumEx13] = @"Data\M-HumEx13.Zl",

            [LibraryFile.WM_Hum] = @"Data\WM-Hum.Zl",
            [LibraryFile.WM_HumEx1] = @"Data\WM-HumEx1.Zl",
            [LibraryFile.WM_HumEx2] = @"Data\WM-HumEx2.Zl",
            [LibraryFile.WM_HumEx3] = @"Data\WM-HumEx3.Zl",
            [LibraryFile.WM_HumEx4] = @"Data\WM-HumEx4.Zl",
            [LibraryFile.WM_HumEx10] = @"Data\WM-HumEx10.Zl",
            [LibraryFile.WM_HumEx11] = @"Data\WM-HumEx11.Zl",
            [LibraryFile.WM_HumEx12] = @"Data\WM-HumEx12.Zl",
            [LibraryFile.WM_HumEx13] = @"Data\WM-HumEx13.Zl",

            //Custom
            [LibraryFile.M_HumCx1] = @"Data\M-HumCx1.Zl",
            [LibraryFile.WM_HumCx1] = @"Data\WM-HumCx1.Zl",

            [LibraryFile.M_Hair] = @"Data\M-Hair.Zl",
            [LibraryFile.WM_Hair] = @"Data\WM-Hair.Zl",

            [LibraryFile.M_HumA] = @"Data\M-HumA.Zl",
            [LibraryFile.M_HumAEx1] = @"Data\M-HumAEx1.Zl",
            [LibraryFile.M_HumAEx2] = @"Data\M-HumAEx2.Zl",
            [LibraryFile.M_HumAEx3] = @"Data\M-HumAEx3.Zl",

            [LibraryFile.WM_HumA] = @"Data\WM-HumA.Zl",
            [LibraryFile.WM_HumAEx1] = @"Data\WM-HumAEx1.Zl",
            [LibraryFile.WM_HumAEx2] = @"Data\WM-HumAEx2.Zl",
            [LibraryFile.WM_HumAEx3] = @"Data\WM-HumAEx3.Zl",

            //Custom
            [LibraryFile.M_HumACx1] = @"Data\M-HumACx1.Zl",
            [LibraryFile.WM_HumACx1] = @"Data\WM-HumACx1.Zl",

            [LibraryFile.M_HairA] = @"Data\M-HairA.Zl",
            [LibraryFile.WM_HairA] = @"Data\WM-HairA.Zl",

            [LibraryFile.M_Costume] = @"Data\M-Costume.Zl",
            [LibraryFile.M_CostumeA] = @"Data\M-CostumeA.Zl",
            [LibraryFile.M_CostumeEx1] = @"Data\M-CostumeEx1.Zl",

            [LibraryFile.WM_Costume] = @"Data\WM-Costume.Zl",
            [LibraryFile.WM_CostumeA] = @"Data\WM-CostumeA.Zl",
            [LibraryFile.WM_CostumeEx1] = @"Data\WM-CostumeEx1.Zl",

            [LibraryFile.Horse] = @"Data\Horse.Zl",
            [LibraryFile.HorseIron] = @"Data\Horse_Iron.Zl",
            [LibraryFile.HorseSilver] = @"Data\Horse_Silver.Zl",
            [LibraryFile.HorseGold] = @"Data\Horse_Golden.Zl",
            [LibraryFile.HorseBlue] = @"Data\Horse_Blue.Zl",
            [LibraryFile.HorseDark] = @"Data\Horse_Dark.Zl",
            [LibraryFile.HorseDarkEffect] = @"Data\Horse_DarkEffect.Zl",
            [LibraryFile.HorseRoyal] = @"Data\Horse_Royal.Zl",
            [LibraryFile.HorseRoyalEffect] = @"Data\Horse_RoyalEffect.Zl",
            [LibraryFile.HorseBlueDragon] = @"Data\Horse_BlueDragon.Zl",
            [LibraryFile.HorseBlueDragonEffect] = @"Data\Horse_BlueDragonEffect.Zl",

            [LibraryFile.M_Shield1] = @"Data\M-Shield1.Zl",
            [LibraryFile.M_Shield2] = @"Data\M-Shield2.Zl",
            [LibraryFile.WM_Shield1] = @"Data\WM-Shield1.Zl",
            [LibraryFile.WM_Shield2] = @"Data\WM-Shield2.Zl",

            [LibraryFile.M_Weapon1] = @"Data\M-Weapon1.Zl",
            [LibraryFile.M_Weapon2] = @"Data\M-Weapon2.Zl",
            [LibraryFile.M_Weapon3] = @"Data\M-Weapon3.Zl",
            [LibraryFile.M_Weapon4] = @"Data\M-Weapon4.Zl",
            [LibraryFile.M_Weapon5] = @"Data\M-Weapon5.Zl",
            [LibraryFile.M_Weapon6] = @"Data\M-Weapon6.Zl",
            [LibraryFile.M_Weapon7] = @"Data\M-Weapon7.Zl",
            [LibraryFile.M_Weapon10] = @"Data\M-Weapon10.Zl",
            [LibraryFile.M_Weapon11] = @"Data\M-Weapon11.Zl",
            [LibraryFile.M_Weapon12] = @"Data\M-Weapon12.Zl",
            [LibraryFile.M_Weapon13] = @"Data\M-Weapon13.Zl",
            [LibraryFile.M_Weapon14] = @"Data\M-Weapon14.Zl",
            [LibraryFile.M_Weapon15] = @"Data\M-Weapon15.Zl",
            [LibraryFile.M_Weapon16] = @"Data\M-Weapon16.Zl",

            [LibraryFile.WM_Weapon1] = @"Data\WM-Weapon1.Zl",
            [LibraryFile.WM_Weapon2] = @"Data\WM-Weapon2.Zl",
            [LibraryFile.WM_Weapon3] = @"Data\WM-Weapon3.Zl",
            [LibraryFile.WM_Weapon4] = @"Data\WM-Weapon4.Zl",
            [LibraryFile.WM_Weapon5] = @"Data\WM-Weapon5.Zl",
            [LibraryFile.WM_Weapon6] = @"Data\WM-Weapon6.Zl",
            [LibraryFile.WM_Weapon7] = @"Data\WM-Weapon7.Zl",
            [LibraryFile.WM_Weapon10] = @"Data\WM-Weapon10.Zl",
            [LibraryFile.WM_Weapon11] = @"Data\WM-Weapon11.Zl",
            [LibraryFile.WM_Weapon12] = @"Data\WM-Weapon12.Zl",
            [LibraryFile.WM_Weapon13] = @"Data\WM-Weapon13.Zl",
            [LibraryFile.WM_Weapon14] = @"Data\WM-Weapon14.Zl",
            [LibraryFile.WM_Weapon15] = @"Data\WM-Weapon15.Zl",
            [LibraryFile.WM_Weapon16] = @"Data\WM-Weapon16.Zl",



            [LibraryFile.M_WeaponADL1] = @"Data\M-WeaponADL1.Zl",
            [LibraryFile.M_WeaponADL2] = @"Data\M-WeaponADL2.Zl",
            [LibraryFile.M_WeaponADL6] = @"Data\M-WeaponADL6.Zl",
            [LibraryFile.M_WeaponADR1] = @"Data\M-WeaponADR1.Zl",
            [LibraryFile.M_WeaponADR2] = @"Data\M-WeaponADR2.Zl",
            [LibraryFile.M_WeaponADR6] = @"Data\M-WeaponADR6.Zl",

            [LibraryFile.M_WeaponAOH1] = @"Data\M-WeaponAOH1.Zl",
            [LibraryFile.M_WeaponAOH2] = @"Data\M-WeaponAOH2.Zl",
            [LibraryFile.M_WeaponAOH3] = @"Data\M-WeaponAOH3.Zl",
            [LibraryFile.M_WeaponAOH4] = @"Data\M-WeaponAOH4.Zl",
            [LibraryFile.M_WeaponAOH5] = @"Data\M-WeaponAOH5.Zl",
            [LibraryFile.M_WeaponAOH6] = @"Data\M-WeaponAOH6.Zl",


            [LibraryFile.WM_WeaponADL1] = @"Data\WM-WeaponADL1.Zl",
            [LibraryFile.WM_WeaponADL2] = @"Data\WM-WeaponADL2.Zl",
            [LibraryFile.WM_WeaponADL6] = @"Data\WM-WeaponADL6.Zl",
            [LibraryFile.WM_WeaponADR1] = @"Data\WM-WeaponADR1.Zl",
            [LibraryFile.WM_WeaponADR2] = @"Data\WM-WeaponADR2.Zl",
            [LibraryFile.WM_WeaponADR6] = @"Data\WM-WeaponADR6.Zl",

            [LibraryFile.WM_WeaponAOH1] = @"Data\WM-WeaponAOH1.Zl",
            [LibraryFile.WM_WeaponAOH2] = @"Data\WM-WeaponAOH2.Zl",
            [LibraryFile.WM_WeaponAOH3] = @"Data\WM-WeaponAOH3.Zl",
            [LibraryFile.WM_WeaponAOH4] = @"Data\WM-WeaponAOH4.Zl",
            [LibraryFile.WM_WeaponAOH5] = @"Data\WM-WeaponAOH5.Zl",
            [LibraryFile.WM_WeaponAOH6] = @"Data\WM-WeaponAOH6.Zl",


            [LibraryFile.M_Helmet1] = @"Data\M-Helmet1.Zl",
            [LibraryFile.M_Helmet2] = @"Data\M-Helmet2.Zl",
            [LibraryFile.M_Helmet3] = @"Data\M-Helmet3.Zl",
            [LibraryFile.M_Helmet4] = @"Data\M-Helmet4.Zl",
            [LibraryFile.M_Helmet5] = @"Data\M-Helmet5.Zl",

            [LibraryFile.M_Helmet11] = @"Data\M-Helmet11.Zl",
            [LibraryFile.M_Helmet12] = @"Data\M-Helmet12.Zl",
            [LibraryFile.M_Helmet13] = @"Data\M-Helmet13.Zl",
            [LibraryFile.M_Helmet14] = @"Data\M-Helmet14.Zl",


            [LibraryFile.WM_Helmet1] = @"Data\WM-Helmet1.Zl",
            [LibraryFile.WM_Helmet2] = @"Data\WM-Helmet2.Zl",
            [LibraryFile.WM_Helmet3] = @"Data\WM-Helmet3.Zl",
            [LibraryFile.WM_Helmet4] = @"Data\WM-Helmet4.Zl",
            [LibraryFile.WM_Helmet5] = @"Data\WM-Helmet5.Zl",

            [LibraryFile.WM_Helmet11] = @"Data\WM-Helmet11.Zl",
            [LibraryFile.WM_Helmet12] = @"Data\WM-Helmet12.Zl",
            [LibraryFile.WM_Helmet13] = @"Data\WM-Helmet13.Zl",
            [LibraryFile.WM_Helmet14] = @"Data\WM-Helmet14.Zl",

            //Custom
            [LibraryFile.M_HelmetCx1] = @"Data\M-HelmetCx1.Zl",
            [LibraryFile.WM_HelmetCx1] = @"Data\WM-HelmetCx1.Zl",

            [LibraryFile.M_HelmetA1] = @"Data\M-HelmetA1.Zl",
            [LibraryFile.M_HelmetA2] = @"Data\M-HelmetA2.Zl",
            [LibraryFile.M_HelmetA3] = @"Data\M-HelmetA3.Zl",
            [LibraryFile.M_HelmetA4] = @"Data\M-HelmetA4.Zl",


            [LibraryFile.WM_HelmetA1] = @"Data\WM-HelmetA1.Zl",
            [LibraryFile.WM_HelmetA2] = @"Data\WM-HelmetA2.Zl",
            [LibraryFile.WM_HelmetA3] = @"Data\WM-HelmetA3.Zl",
            [LibraryFile.WM_HelmetA4] = @"Data\WM-HelmetA4.Zl",

            //Custom
            [LibraryFile.M_HelmetACx1] = @"Data\M-HelmetACx1.Zl",
            [LibraryFile.WM_HelmetACx1] = @"Data\WM-HelmetACx1.Zl",


            [LibraryFile.MonMagic] = @"Data\MonMagic.Zl", //
            [LibraryFile.MonMagicEx] = @"Data\MonMagicEx.Zl", //
            [LibraryFile.MonMagicEx2] = @"Data\MonMagicEx2.Zl", //
            [LibraryFile.MonMagicEx3] = @"Data\MonMagicEx3.Zl", //
            [LibraryFile.MonMagicEx4] = @"Data\MonMagicEx4.Zl", //
            [LibraryFile.MonMagicEx5] = @"Data\MonMagicEx5.Zl", //
            [LibraryFile.MonMagicEx6] = @"Data\MonMagicEx6.Zl", //
            [LibraryFile.MonMagicEx7] = @"Data\MonMagicEx7.Zl", //
            [LibraryFile.MonMagicEx8] = @"Data\MonMagicEx8.Zl", //
            [LibraryFile.MonMagicEx9] = @"Data\MonMagicEx9.Zl", //
            [LibraryFile.MonMagicEx19] = @"Data\MonMagicEx19.Zl", //
            [LibraryFile.MonMagicEx20] = @"Data\MonMagicEx20.Zl", //
            [LibraryFile.MonMagicEx21] = @"Data\MonMagicEx21.Zl", //
            [LibraryFile.MonMagicEx22] = @"Data\MonMagicEx22.Zl", //
            [LibraryFile.MonMagicEx23] = @"Data\MonMagicEx23.Zl", //
            [LibraryFile.MonMagicEx26] = @"Data\MonMagicEx26.Zl", //

            [LibraryFile.Mon_1] = @"Data\Mon-1.Zl",
            [LibraryFile.Mon_2] = @"Data\Mon-2.Zl",
            [LibraryFile.Mon_3] = @"Data\Mon-3.Zl",
            [LibraryFile.Mon_4] = @"Data\Mon-4.Zl",
            [LibraryFile.Mon_5] = @"Data\Mon-5.Zl",
            [LibraryFile.Mon_6] = @"Data\Mon-6.Zl",
            [LibraryFile.Mon_7] = @"Data\Mon-7.Zl",
            [LibraryFile.Mon_8] = @"Data\Mon-8.Zl",
            [LibraryFile.Mon_9] = @"Data\Mon-9.Zl",
            [LibraryFile.Mon_10] = @"Data\Mon-10.Zl",

            [LibraryFile.Mon_11] = @"Data\Mon-11.Zl",
            [LibraryFile.Mon_12] = @"Data\Mon-12.Zl",
            [LibraryFile.Mon_13] = @"Data\Mon-13.Zl",
            [LibraryFile.Mon_14] = @"Data\Mon-14.Zl",
            [LibraryFile.Mon_15] = @"Data\Mon-15.Zl",
            [LibraryFile.Mon_16] = @"Data\Mon-16.Zl",
            [LibraryFile.Mon_17] = @"Data\Mon-17.Zl",
            [LibraryFile.Mon_18] = @"Data\Mon-18.Zl",
            [LibraryFile.Mon_19] = @"Data\Mon-19.Zl",
            [LibraryFile.Mon_20] = @"Data\Mon-20.Zl",

            [LibraryFile.Mon_21] = @"Data\Mon-21.Zl",
            [LibraryFile.Mon_22] = @"Data\Mon-22.Zl",
            [LibraryFile.Mon_23] = @"Data\Mon-23.Zl",
            [LibraryFile.Mon_24] = @"Data\Mon-24.Zl",
            [LibraryFile.Mon_25] = @"Data\Mon-25.Zl",
            [LibraryFile.Mon_26] = @"Data\Mon-26.Zl",
            [LibraryFile.Mon_27] = @"Data\Mon-27.Zl",
            [LibraryFile.Mon_28] = @"Data\Mon-28.Zl",
            [LibraryFile.Mon_29] = @"Data\Mon-29.Zl",
            [LibraryFile.Mon_30] = @"Data\Mon-30.Zl",

            [LibraryFile.Mon_31] = @"Data\Mon-31.Zl",
            [LibraryFile.Mon_32] = @"Data\Mon-32.Zl",
            [LibraryFile.Mon_33] = @"Data\Mon-33.Zl",
            [LibraryFile.Mon_34] = @"Data\Mon-34.Zl",
            [LibraryFile.Mon_35] = @"Data\Mon-35.Zl",
            [LibraryFile.Mon_36] = @"Data\Mon-36.Zl",
            [LibraryFile.Mon_37] = @"Data\Mon-37.Zl",
            [LibraryFile.Mon_38] = @"Data\Mon-38.Zl",
            [LibraryFile.Mon_39] = @"Data\Mon-39.Zl",
            [LibraryFile.Mon_40] = @"Data\Mon-40.Zl",

            [LibraryFile.Mon_41] = @"Data\Mon-41.Zl",
            [LibraryFile.Mon_42] = @"Data\Mon-42.Zl",
            [LibraryFile.Mon_43] = @"Data\Mon-43.Zl",
            [LibraryFile.Mon_44] = @"Data\Mon-44.Zl",
            [LibraryFile.Mon_45] = @"Data\Mon-45.Zl",
            [LibraryFile.Mon_46] = @"Data\Mon-46.Zl",
            [LibraryFile.Mon_47] = @"Data\Mon-47.Zl",
            [LibraryFile.Mon_48] = @"Data\Mon-48.Zl",
            [LibraryFile.Mon_49] = @"Data\Mon-49.Zl",
            [LibraryFile.Mon_50] = @"Data\Mon-50.Zl",

            [LibraryFile.Mon_51] = @"Data\Mon-51.Zl",
            [LibraryFile.Mon_52] = @"Data\Mon-52.Zl",
            [LibraryFile.Mon_53] = @"Data\Mon-53.Zl",
            [LibraryFile.Mon_54] = @"Data\Mon-54.Zl",
            [LibraryFile.Mon_55] = @"Data\Mon-55.Zl",
            [LibraryFile.Mon_56] = @"Data\Mon-56.Zl",
            [LibraryFile.Mon_57] = @"Data\Mon-57.Zl",

            [LibraryFile.Magic] = @"Data\Magic.Zl",
            [LibraryFile.MagicEx] = @"Data\MagicEx.Zl",
            [LibraryFile.MagicEx2] = @"Data\MagicEx2.Zl",
            [LibraryFile.MagicEx3] = @"Data\MagicEx3.Zl",
            [LibraryFile.MagicEx4] = @"Data\MagicEx4.Zl",
            [LibraryFile.MagicEx5] = @"Data\MagicEx5.Zl",
            [LibraryFile.MagicEx6] = @"Data\MagicEx6.Zl",
            [LibraryFile.MagicEx7] = @"Data\MagicEx7.Zl",
            [LibraryFile.MagicEx8] = @"Data\MagicEx8.Zl",
            [LibraryFile.MagicEx9] = @"Data\MagicEx9.Zl",
            [LibraryFile.MagicEx10] = @"Data\MagicEx10.Zl",
            [LibraryFile.MagicEx11] = @"Data\MagicEx11.Zl",

            [LibraryFile.WemadeMir2_Tiles] = @"Data\Map Data\WemadeMir2\Tiles.Zl",
            [LibraryFile.WemadeMir2_SmTiles] = @"Data\Map Data\WemadeMir2\SmTiles.Zl",
            [LibraryFile.WemadeMir2_Objects] = @"Data\Map Data\WemadeMir2\Objects.Zl",
            [LibraryFile.WemadeMir2_Objects2] = @"Data\Map Data\WemadeMir2\Objects2.Zl",
            [LibraryFile.WemadeMir2_Objects3] = @"Data\Map Data\WemadeMir2\Objects3.Zl",
            [LibraryFile.WemadeMir2_Objects4] = @"Data\Map Data\WemadeMir2\Objects4.Zl",
            [LibraryFile.WemadeMir2_Objects5] = @"Data\Map Data\WemadeMir2\Objects5.Zl",
            [LibraryFile.WemadeMir2_Objects6] = @"Data\Map Data\WemadeMir2\Objects6.Zl",
            [LibraryFile.WemadeMir2_Objects7] = @"Data\Map Data\WemadeMir2\Objects7.Zl",
            [LibraryFile.WemadeMir2_Objects8] = @"Data\Map Data\WemadeMir2\Objects8.Zl",
            [LibraryFile.WemadeMir2_Objects9] = @"Data\Map Data\WemadeMir2\Objects9.Zl",
            [LibraryFile.WemadeMir2_Objects10] = @"Data\Map Data\WemadeMir2\Objects10.Zl",
            [LibraryFile.WemadeMir2_Objects11] = @"Data\Map Data\WemadeMir2\Objects11.Zl",
            [LibraryFile.WemadeMir2_Objects12] = @"Data\Map Data\WemadeMir2\Objects12.Zl",
            [LibraryFile.WemadeMir2_Objects13] = @"Data\Map Data\WemadeMir2\Objects13.Zl",
            [LibraryFile.WemadeMir2_Objects14] = @"Data\Map Data\WemadeMir2\Objects14.Zl",
            [LibraryFile.WemadeMir2_Objects15] = @"Data\Map Data\WemadeMir2\Objects15.Zl",
            [LibraryFile.WemadeMir2_Objects16] = @"Data\Map Data\WemadeMir2\Objects16.Zl",
            [LibraryFile.WemadeMir2_Objects17] = @"Data\Map Data\WemadeMir2\Objects17.Zl",
            [LibraryFile.WemadeMir2_Objects18] = @"Data\Map Data\WemadeMir2\Objects18.Zl",
            [LibraryFile.WemadeMir2_Objects19] = @"Data\Map Data\WemadeMir2\Objects19.Zl",
            [LibraryFile.WemadeMir2_Objects20] = @"Data\Map Data\WemadeMir2\Objects20.Zl",
            [LibraryFile.WemadeMir2_Objects21] = @"Data\Map Data\WemadeMir2\Objects21.Zl",
            [LibraryFile.WemadeMir2_Objects22] = @"Data\Map Data\WemadeMir2\Objects22.Zl",
            [LibraryFile.WemadeMir2_Objects23] = @"Data\Map Data\WemadeMir2\Objects23.Zl",
            [LibraryFile.WemadeMir2_Objects24] = @"Data\Map Data\WemadeMir2\Objects24.Zl",
            [LibraryFile.WemadeMir2_Objects25] = @"Data\Map Data\WemadeMir2\Objects25.Zl",
            [LibraryFile.WemadeMir2_Objects26] = @"Data\Map Data\WemadeMir2\Objects26.Zl",
            [LibraryFile.WemadeMir2_Objects27] = @"Data\Map Data\WemadeMir2\Objects27.Zl",
            [LibraryFile.WemadeMir2_Objects28] = @"Data\Map Data\WemadeMir2\Objects28.Zl",
            [LibraryFile.WemadeMir2_Objects29] = @"Data\Map Data\WemadeMir2\Objects29.Zl",
            [LibraryFile.WemadeMir2_Objects30] = @"Data\Map Data\WemadeMir2\Objects30.Zl",

            [LibraryFile.ShandaMir2_Tiles] = @"Data\Map Data\ShandaMir2\Tiles.Zl",
            [LibraryFile.ShandaMir2_Tiles2] = @"Data\Map Data\ShandaMir2\Tiles2.Zl",
            [LibraryFile.ShandaMir2_Tiles3] = @"Data\Map Data\ShandaMir2\Tiles3.Zl",
            [LibraryFile.ShandaMir2_Tiles4] = @"Data\Map Data\ShandaMir2\Tiles4.Zl",
            [LibraryFile.ShandaMir2_Tiles5] = @"Data\Map Data\ShandaMir2\Tiles5.Zl",
            [LibraryFile.ShandaMir2_Tiles6] = @"Data\Map Data\ShandaMir2\Tiles6.Zl",
            [LibraryFile.ShandaMir2_Tiles7] = @"Data\Map Data\ShandaMir2\Tiles7.Zl",
            [LibraryFile.ShandaMir2_Tiles8] = @"Data\Map Data\ShandaMir2\Tiles8.Zl",
            [LibraryFile.ShandaMir2_Tiles9] = @"Data\Map Data\ShandaMir2\Tiles9.Zl",
            [LibraryFile.ShandaMir2_Tiles10] = @"Data\Map Data\ShandaMir2\Tiles10.Zl",
            [LibraryFile.ShandaMir2_SmTiles] = @"Data\Map Data\ShandaMir2\SmTiles.Zl",
            [LibraryFile.ShandaMir2_SmTiles2] = @"Data\Map Data\ShandaMir2\SmTiles2.Zl",
            [LibraryFile.ShandaMir2_SmTiles3] = @"Data\Map Data\ShandaMir2\SmTiles3.Zl",
            [LibraryFile.ShandaMir2_SmTiles4] = @"Data\Map Data\ShandaMir2\SmTiles4.Zl",
            [LibraryFile.ShandaMir2_SmTiles5] = @"Data\Map Data\ShandaMir2\SmTiles5.Zl",
            [LibraryFile.ShandaMir2_SmTiles6] = @"Data\Map Data\ShandaMir2\SmTiles6.Zl",
            [LibraryFile.ShandaMir2_SmTiles7] = @"Data\Map Data\ShandaMir2\SmTiles7.Zl",
            [LibraryFile.ShandaMir2_SmTiles8] = @"Data\Map Data\ShandaMir2\SmTiles8.Zl",
            [LibraryFile.ShandaMir2_SmTiles9] = @"Data\Map Data\ShandaMir2\SmTiles9.Zl",
            [LibraryFile.ShandaMir2_SmTiles10] = @"Data\Map Data\ShandaMir2\SmTiles10.Zl",
            [LibraryFile.ShandaMir2_AniTiles] = @"Data\Map Data\ShandaMir2\AniTiles1.Zl",
            [LibraryFile.ShandaMir2_Objects] = @"Data\Map Data\ShandaMir2\Objects.Zl",
            [LibraryFile.ShandaMir2_Objects2] = @"Data\Map Data\ShandaMir2\Objects2.Zl",
            [LibraryFile.ShandaMir2_Objects3] = @"Data\Map Data\ShandaMir2\Objects3.Zl",
            [LibraryFile.ShandaMir2_Objects4] = @"Data\Map Data\ShandaMir2\Objects4.Zl",
            [LibraryFile.ShandaMir2_Objects5] = @"Data\Map Data\ShandaMir2\Objects5.Zl",
            [LibraryFile.ShandaMir2_Objects6] = @"Data\Map Data\ShandaMir2\Objects6.Zl",
            [LibraryFile.ShandaMir2_Objects7] = @"Data\Map Data\ShandaMir2\Objects7.Zl",
            [LibraryFile.ShandaMir2_Objects8] = @"Data\Map Data\ShandaMir2\Objects8.Zl",
            [LibraryFile.ShandaMir2_Objects9] = @"Data\Map Data\ShandaMir2\Objects9.Zl",
            [LibraryFile.ShandaMir2_Objects10] = @"Data\Map Data\ShandaMir2\Objects10.Zl",
            [LibraryFile.ShandaMir2_Objects11] = @"Data\Map Data\ShandaMir2\Objects11.Zl",
            [LibraryFile.ShandaMir2_Objects12] = @"Data\Map Data\ShandaMir2\Objects12.Zl",
            [LibraryFile.ShandaMir2_Objects13] = @"Data\Map Data\ShandaMir2\Objects13.Zl",
            [LibraryFile.ShandaMir2_Objects14] = @"Data\Map Data\ShandaMir2\Objects14.Zl",
            [LibraryFile.ShandaMir2_Objects15] = @"Data\Map Data\ShandaMir2\Objects15.Zl",
            [LibraryFile.ShandaMir2_Objects16] = @"Data\Map Data\ShandaMir2\Objects16.Zl",
            [LibraryFile.ShandaMir2_Objects17] = @"Data\Map Data\ShandaMir2\Objects17.Zl",
            [LibraryFile.ShandaMir2_Objects18] = @"Data\Map Data\ShandaMir2\Objects18.Zl",
            [LibraryFile.ShandaMir2_Objects19] = @"Data\Map Data\ShandaMir2\Objects19.Zl",
            [LibraryFile.ShandaMir2_Objects20] = @"Data\Map Data\ShandaMir2\Objects20.Zl",
            [LibraryFile.ShandaMir2_Objects21] = @"Data\Map Data\ShandaMir2\Objects21.Zl",
            [LibraryFile.ShandaMir2_Objects22] = @"Data\Map Data\ShandaMir2\Objects22.Zl",
            [LibraryFile.ShandaMir2_Objects23] = @"Data\Map Data\ShandaMir2\Objects23.Zl",
            [LibraryFile.ShandaMir2_Objects24] = @"Data\Map Data\ShandaMir2\Objects24.Zl",
            [LibraryFile.ShandaMir2_Objects25] = @"Data\Map Data\ShandaMir2\Objects25.Zl",
            [LibraryFile.ShandaMir2_Objects26] = @"Data\Map Data\ShandaMir2\Objects26.Zl",
            [LibraryFile.ShandaMir2_Objects27] = @"Data\Map Data\ShandaMir2\Objects27.Zl",
            [LibraryFile.ShandaMir2_Objects28] = @"Data\Map Data\ShandaMir2\Objects28.Zl",
            [LibraryFile.ShandaMir2_Objects29] = @"Data\Map Data\ShandaMir2\Objects29.Zl",
            [LibraryFile.ShandaMir2_Objects30] = @"Data\Map Data\ShandaMir2\Objects30.Zl",
            [LibraryFile.ShandaMir2_Objects31] = @"Data\Map Data\ShandaMir2\Objects31.Zl",
            [LibraryFile.ShandaMir2_Objects32] = @"Data\Map Data\ShandaMir2\Objects32.Zl",
            [LibraryFile.ShandaMir2_Objects33] = @"Data\Map Data\ShandaMir2\Objects33.Zl",
            [LibraryFile.ShandaMir2_Objects34] = @"Data\Map Data\ShandaMir2\Objects34.Zl",
            [LibraryFile.ShandaMir2_Objects35] = @"Data\Map Data\ShandaMir2\Objects35.Zl",
            [LibraryFile.ShandaMir2_Objects36] = @"Data\Map Data\ShandaMir2\Objects36.Zl",
            [LibraryFile.ShandaMir2_Objects37] = @"Data\Map Data\ShandaMir2\Objects37.Zl",
            [LibraryFile.ShandaMir2_Objects38] = @"Data\Map Data\ShandaMir2\Objects38.Zl",
            [LibraryFile.ShandaMir2_Objects39] = @"Data\Map Data\ShandaMir2\Objects39.Zl",
            [LibraryFile.ShandaMir2_Objects40] = @"Data\Map Data\ShandaMir2\Objects40.Zl",
            [LibraryFile.ShandaMir2_Objects41] = @"Data\Map Data\ShandaMir2\Objects41.Zl",
            [LibraryFile.ShandaMir2_Objects42] = @"Data\Map Data\ShandaMir2\Objects42.Zl",
            [LibraryFile.ShandaMir2_Objects43] = @"Data\Map Data\ShandaMir2\Objects43.Zl",
            [LibraryFile.ShandaMir2_Objects44] = @"Data\Map Data\ShandaMir2\Objects44.Zl",
            [LibraryFile.ShandaMir2_Objects45] = @"Data\Map Data\ShandaMir2\Objects45.Zl",
            [LibraryFile.ShandaMir2_Objects46] = @"Data\Map Data\ShandaMir2\Objects46.Zl",
            [LibraryFile.ShandaMir2_Objects47] = @"Data\Map Data\ShandaMir2\Objects47.Zl",
            [LibraryFile.ShandaMir2_Objects48] = @"Data\Map Data\ShandaMir2\Objects48.Zl",
            [LibraryFile.ShandaMir2_Objects49] = @"Data\Map Data\ShandaMir2\Objects49.Zl",
            [LibraryFile.ShandaMir2_Objects50] = @"Data\Map Data\ShandaMir2\Objects50.Zl",
            [LibraryFile.ShandaMir2_Objects51] = @"Data\Map Data\ShandaMir2\Objects51.Zl",
            [LibraryFile.ShandaMir2_Objects52] = @"Data\Map Data\ShandaMir2\Objects52.Zl",
            [LibraryFile.ShandaMir2_Objects53] = @"Data\Map Data\ShandaMir2\Objects53.Zl",
            [LibraryFile.ShandaMir2_Objects54] = @"Data\Map Data\ShandaMir2\Objects54.Zl",
            [LibraryFile.ShandaMir2_Objects55] = @"Data\Map Data\ShandaMir2\Objects55.Zl",
            [LibraryFile.ShandaMir2_Objects56] = @"Data\Map Data\ShandaMir2\Objects56.Zl",
            [LibraryFile.ShandaMir2_Objects57] = @"Data\Map Data\ShandaMir2\Objects57.Zl",
            [LibraryFile.ShandaMir2_Objects58] = @"Data\Map Data\ShandaMir2\Objects58.Zl",
            [LibraryFile.ShandaMir2_Objects59] = @"Data\Map Data\ShandaMir2\Objects59.Zl",
            [LibraryFile.ShandaMir2_Objects60] = @"Data\Map Data\ShandaMir2\Objects60.Zl",
            [LibraryFile.ShandaMir2_Objects61] = @"Data\Map Data\ShandaMir2\Objects61.Zl",
            [LibraryFile.ShandaMir2_Objects62] = @"Data\Map Data\ShandaMir2\Objects62.Zl",
            [LibraryFile.ShandaMir2_Objects63] = @"Data\Map Data\ShandaMir2\Objects63.Zl",
            [LibraryFile.ShandaMir2_Objects64] = @"Data\Map Data\ShandaMir2\Objects64.Zl",
            [LibraryFile.ShandaMir2_Objects65] = @"Data\Map Data\ShandaMir2\Objects65.Zl",
            [LibraryFile.ShandaMir2_Objects66] = @"Data\Map Data\ShandaMir2\Objects66.Zl",
            [LibraryFile.ShandaMir2_Objects67] = @"Data\Map Data\ShandaMir2\Objects67.Zl",
            [LibraryFile.ShandaMir2_Objects68] = @"Data\Map Data\ShandaMir2\Objects68.Zl",
            [LibraryFile.ShandaMir2_Objects69] = @"Data\Map Data\ShandaMir2\Objects69.Zl",
            [LibraryFile.ShandaMir2_Objects70] = @"Data\Map Data\ShandaMir2\Objects70.Zl",
            [LibraryFile.ShandaMir2_Objects71] = @"Data\Map Data\ShandaMir2\Objects71.Zl",
            [LibraryFile.ShandaMir2_Objects72] = @"Data\Map Data\ShandaMir2\Objects72.Zl",
            [LibraryFile.ShandaMir2_Objects73] = @"Data\Map Data\ShandaMir2\Objects73.Zl",
            [LibraryFile.ShandaMir2_Objects74] = @"Data\Map Data\ShandaMir2\Objects74.Zl",
            [LibraryFile.ShandaMir2_Objects75] = @"Data\Map Data\ShandaMir2\Objects75.Zl",
            [LibraryFile.ShandaMir2_Objects76] = @"Data\Map Data\ShandaMir2\Objects76.Zl",
            [LibraryFile.ShandaMir2_Objects77] = @"Data\Map Data\ShandaMir2\Objects77.Zl",
            [LibraryFile.ShandaMir2_Objects78] = @"Data\Map Data\ShandaMir2\Objects78.Zl",
            [LibraryFile.ShandaMir2_Objects79] = @"Data\Map Data\ShandaMir2\Objects79.Zl",
            [LibraryFile.ShandaMir2_Objects80] = @"Data\Map Data\ShandaMir2\Objects80.Zl",
            [LibraryFile.ShandaMir2_Objects81] = @"Data\Map Data\ShandaMir2\Objects81.Zl",
            [LibraryFile.ShandaMir2_Objects82] = @"Data\Map Data\ShandaMir2\Objects82.Zl",
            [LibraryFile.ShandaMir2_Objects83] = @"Data\Map Data\ShandaMir2\Objects83.Zl",
            [LibraryFile.ShandaMir2_Objects84] = @"Data\Map Data\ShandaMir2\Objects84.Zl",
            [LibraryFile.ShandaMir2_Objects85] = @"Data\Map Data\ShandaMir2\Objects85.Zl",
            [LibraryFile.ShandaMir2_Objects86] = @"Data\Map Data\ShandaMir2\Objects86.Zl",
            [LibraryFile.ShandaMir2_Objects87] = @"Data\Map Data\ShandaMir2\Objects87.Zl",
            [LibraryFile.ShandaMir2_Objects88] = @"Data\Map Data\ShandaMir2\Objects88.Zl",
            [LibraryFile.ShandaMir2_Objects89] = @"Data\Map Data\ShandaMir2\Objects89.Zl",
            [LibraryFile.ShandaMir2_Objects90] = @"Data\Map Data\ShandaMir2\Objects90.Zl",
            [LibraryFile.ShandaMir2_Objects91] = @"Data\Map Data\ShandaMir2\Objects91.Zl",
            [LibraryFile.ShandaMir2_Objects92] = @"Data\Map Data\ShandaMir2\Objects92.Zl",
            [LibraryFile.ShandaMir2_Objects93] = @"Data\Map Data\ShandaMir2\Objects93.Zl",
            [LibraryFile.ShandaMir2_Objects94] = @"Data\Map Data\ShandaMir2\Objects94.Zl",

            [LibraryFile.WemadeMir3_Animationsc] = @"Data\Map Data\Animationsc.Zl",
            [LibraryFile.WemadeMir3_Cliffsc] = @"Data\Map Data\Cliffsc.Zl",
            [LibraryFile.WemadeMir3_Dungeonsc] = @"Data\Map Data\Dungeonsc.Zl",
            [LibraryFile.WemadeMir3_Furnituresc] = @"Data\Map Data\Furnituresc.Zl",
            [LibraryFile.WemadeMir3_Housesc] = @"Data\Map Data\Housesc.Zl",
            [LibraryFile.WemadeMir3_Innersc] = @"Data\Map Data\Innersc.Zl",
            [LibraryFile.WemadeMir3_Object1c] = @"Data\Map Data\Object1c.Zl",
            [LibraryFile.WemadeMir3_Object2c] = @"Data\Map Data\Object2c.Zl",
            [LibraryFile.WemadeMir3_SmObjectsc] = @"Data\Map Data\SmObjectsc.Zl",
            [LibraryFile.WemadeMir3_SmTilesc] = @"Data\Map Data\SmTilesc.Zl",
            [LibraryFile.WemadeMir3_Tiles5c] = @"Data\Map Data\Tiles5c.Zl",
            [LibraryFile.WemadeMir3_Tiles30c] = @"Data\Map Data\Tiles30c.Zl",
            [LibraryFile.WemadeMir3_Tilesc] = @"Data\Map Data\Tilesc.Zl",
            [LibraryFile.WemadeMir3_Wallsc] = @"Data\Map Data\Wallsc.Zl",

            [LibraryFile.WemadeMir3_Forest_Animationsc] = @"Data\Map Data\Forest\Animationsc.Zl",
            [LibraryFile.WemadeMir3_Forest_Cliffsc] = @"Data\Map Data\Forest\Cliffsc.Zl",
            [LibraryFile.WemadeMir3_Forest_Dungeonsc] = @"Data\Map Data\Forest\Dungeonsc.Zl",
            [LibraryFile.WemadeMir3_Forest_Furnituresc] = @"Data\Map Data\Forest\Furnituresc.Zl",
            [LibraryFile.WemadeMir3_Forest_Housesc] = @"Data\Map Data\Forest\Housesc.Zl",
            [LibraryFile.WemadeMir3_Forest_Innersc] = @"Data\Map Data\Forest\Innersc.Zl",
            [LibraryFile.WemadeMir3_Forest_SmObjectsc] = @"Data\Map Data\Forest\SmObjectsc.Zl",
            [LibraryFile.WemadeMir3_Forest_SmTilesc] = @"Data\Map Data\Forest\SmTilesc.Zl",
            [LibraryFile.WemadeMir3_Forest_Tiles5c] = @"Data\Map Data\Forest\Tiles5c.Zl",
            [LibraryFile.WemadeMir3_Forest_Tiles30c] = @"Data\Map Data\Forest\Tiles30c.Zl",
            [LibraryFile.WemadeMir3_Forest_Tilesc] = @"Data\Map Data\Forest\Tilesc.Zl",
            [LibraryFile.WemadeMir3_Forest_Wallsc] = @"Data\Map Data\Forest\Wallsc.Zl",

            [LibraryFile.WemadeMir3_Sand_Animationsc] = @"Data\Map Data\Sand\Animationsc.Zl",
            [LibraryFile.WemadeMir3_Sand_Cliffsc] = @"Data\Map Data\Sand\Cliffsc.Zl",
            [LibraryFile.WemadeMir3_Sand_Dungeonsc] = @"Data\Map Data\Sand\Dungeonsc.Zl",
            [LibraryFile.WemadeMir3_Sand_Furnituresc] = @"Data\Map Data\Sand\Furnituresc.Zl",
            [LibraryFile.WemadeMir3_Sand_Housesc] = @"Data\Map Data\Sand\Housesc.Zl",
            [LibraryFile.WemadeMir3_Sand_Innersc] = @"Data\Map Data\Sand\Innersc.Zl",
            [LibraryFile.WemadeMir3_Sand_SmObjectsc] = @"Data\Map Data\Sand\SmObjectsc.Zl",
            [LibraryFile.WemadeMir3_Sand_SmTilesc] = @"Data\Map Data\Sand\SmTilesc.Zl",
            [LibraryFile.WemadeMir3_Sand_Tiles5c] = @"Data\Map Data\Sand\Tiles5c.Zl",
            [LibraryFile.WemadeMir3_Sand_Tiles30c] = @"Data\Map Data\Sand\Tiles30c.Zl",
            [LibraryFile.WemadeMir3_Sand_Tilesc] = @"Data\Map Data\Sand\Tilesc.Zl",
            [LibraryFile.WemadeMir3_Sand_Wallsc] = @"Data\Map Data\Sand\Wallsc.Zl",

            [LibraryFile.WemadeMir3_Snow_Animationsc] = @"Data\Map Data\Snow\Animationsc.Zl",
            [LibraryFile.WemadeMir3_Snow_Cliffsc] = @"Data\Map Data\Snow\Cliffsc.Zl",
            [LibraryFile.WemadeMir3_Snow_Dungeonsc] = @"Data\Map Data\Snow\Dungeonsc.Zl",
            [LibraryFile.WemadeMir3_Snow_Furnituresc] = @"Data\Map Data\Snow\Furnituresc.Zl",
            [LibraryFile.WemadeMir3_Snow_Housesc] = @"Data\Map Data\Snow\Housesc.Zl",
            [LibraryFile.WemadeMir3_Snow_Innersc] = @"Data\Map Data\Snow\Innersc.Zl",
            [LibraryFile.WemadeMir3_Snow_SmObjectsc] = @"Data\Map Data\Snow\SmObjectsc.Zl",
            [LibraryFile.WemadeMir3_Snow_SmTilesc] = @"Data\Map Data\Snow\SmTilesc.Zl",
            [LibraryFile.WemadeMir3_Snow_Tiles5c] = @"Data\Map Data\Snow\Tiles5c.Zl",
            [LibraryFile.WemadeMir3_Snow_Tiles30c] = @"Data\Map Data\Snow\Tiles30c.Zl",
            [LibraryFile.WemadeMir3_Snow_Tilesc] = @"Data\Map Data\Snow\Tilesc.Zl",
            [LibraryFile.WemadeMir3_Snow_Wallsc] = @"Data\Map Data\Snow\Wallsc.Zl",


            [LibraryFile.WemadeMir3_Wood_Animationsc] = @"Data\Map Data\Wood\Animationsc.Zl",
            [LibraryFile.WemadeMir3_Wood_Cliffsc] = @"Data\Map Data\Wood\Cliffsc.Zl",
            [LibraryFile.WemadeMir3_Wood_Dungeonsc] = @"Data\Map Data\Wood\Dungeonsc.Zl",
            [LibraryFile.WemadeMir3_Wood_Furnituresc] = @"Data\Map Data\Wood\Furnituresc.Zl",
            [LibraryFile.WemadeMir3_Wood_Housesc] = @"Data\Map Data\Wood\Housesc.Zl",
            [LibraryFile.WemadeMir3_Wood_Innersc] = @"Data\Map Data\Wood\Innersc.Zl",
            [LibraryFile.WemadeMir3_Wood_SmObjectsc] = @"Data\Map Data\Wood\SmObjectsc.Zl",
            [LibraryFile.WemadeMir3_Wood_SmTilesc] = @"Data\Map Data\Wood\SmTilesc.Zl",
            [LibraryFile.WemadeMir3_Wood_Tiles5c] = @"Data\Map Data\Wood\Tiles5c.Zl",
            [LibraryFile.WemadeMir3_Wood_Tiles30c] = @"Data\Map Data\Wood\Tiles30c.Zl",
            [LibraryFile.WemadeMir3_Wood_Tilesc] = @"Data\Map Data\Wood\Tilesc.Zl",
            [LibraryFile.WemadeMir3_Wood_Wallsc] = @"Data\Map Data\Wood\Wallsc.Zl",

            [LibraryFile.WemadeMir3_Animationsc] = @"Data\Map Data\Animationsc.Zl",
            [LibraryFile.WemadeMir3_Cliffsc] = @"Data\Map Data\Cliffsc.Zl",
            [LibraryFile.WemadeMir3_Dungeonsc] = @"Data\Map Data\Dungeonsc.Zl",
            [LibraryFile.WemadeMir3_Furnituresc] = @"Data\Map Data\Furnituresc.Zl",
            [LibraryFile.WemadeMir3_Housesc] = @"Data\Map Data\Housesc.Zl",
            [LibraryFile.WemadeMir3_Innersc] = @"Data\Map Data\Innersc.Zl",
            [LibraryFile.WemadeMir3_Object1c] = @"Data\Map Data\Object1c.Zl",
            [LibraryFile.WemadeMir3_Object2c] = @"Data\Map Data\Object2c.Zl",
            [LibraryFile.WemadeMir3_SmObjectsc] = @"Data\Map Data\SmObjectsc.Zl",
            [LibraryFile.WemadeMir3_SmTilesc] = @"Data\Map Data\SmTilesc.Zl",
            [LibraryFile.WemadeMir3_Tiles5c] = @"Data\Map Data\Tiles5c.Zl",
            [LibraryFile.WemadeMir3_Tiles30c] = @"Data\Map Data\Tiles30c.Zl",
            [LibraryFile.WemadeMir3_Tilesc] = @"Data\Map Data\Tilesc.Zl",
            [LibraryFile.WemadeMir3_Wallsc] = @"Data\Map Data\Wallsc.Zl",

            [LibraryFile.WemadeMir3_Forest_Animationsc] = @"Data\Map Data\Forest\Animationsc.Zl",
            [LibraryFile.WemadeMir3_Forest_Cliffsc] = @"Data\Map Data\Forest\Cliffsc.Zl",
            [LibraryFile.WemadeMir3_Forest_Dungeonsc] = @"Data\Map Data\Forest\Dungeonsc.Zl",
            [LibraryFile.WemadeMir3_Forest_Furnituresc] = @"Data\Map Data\Forest\Furnituresc.Zl",
            [LibraryFile.WemadeMir3_Forest_Housesc] = @"Data\Map Data\Forest\Housesc.Zl",
            [LibraryFile.WemadeMir3_Forest_Innersc] = @"Data\Map Data\Forest\Innersc.Zl",
            [LibraryFile.WemadeMir3_Forest_SmObjectsc] = @"Data\Map Data\Forest\SmObjectsc.Zl",
            [LibraryFile.WemadeMir3_Forest_SmTilesc] = @"Data\Map Data\Forest\SmTilesc.Zl",
            [LibraryFile.WemadeMir3_Forest_Tiles5c] = @"Data\Map Data\Forest\Tiles5c.Zl",
            [LibraryFile.WemadeMir3_Forest_Tiles30c] = @"Data\Map Data\Forest\Tiles30c.Zl",
            [LibraryFile.WemadeMir3_Forest_Tilesc] = @"Data\Map Data\Forest\Tilesc.Zl",
            [LibraryFile.WemadeMir3_Forest_Wallsc] = @"Data\Map Data\Forest\Wallsc.Zl",

            [LibraryFile.WemadeMir3_Sand_Animationsc] = @"Data\Map Data\Sand\Animationsc.Zl",
            [LibraryFile.WemadeMir3_Sand_Cliffsc] = @"Data\Map Data\Sand\Cliffsc.Zl",
            [LibraryFile.WemadeMir3_Sand_Dungeonsc] = @"Data\Map Data\Sand\Dungeonsc.Zl",
            [LibraryFile.WemadeMir3_Sand_Furnituresc] = @"Data\Map Data\Sand\Furnituresc.Zl",
            [LibraryFile.WemadeMir3_Sand_Housesc] = @"Data\Map Data\Sand\Housesc.Zl",
            [LibraryFile.WemadeMir3_Sand_Innersc] = @"Data\Map Data\Sand\Innersc.Zl",
            [LibraryFile.WemadeMir3_Sand_SmObjectsc] = @"Data\Map Data\Sand\SmObjectsc.Zl",
            [LibraryFile.WemadeMir3_Sand_SmTilesc] = @"Data\Map Data\Sand\SmTilesc.Zl",
            [LibraryFile.WemadeMir3_Sand_Tiles5c] = @"Data\Map Data\Sand\Tiles5c.Zl",
            [LibraryFile.WemadeMir3_Sand_Tiles30c] = @"Data\Map Data\Sand\Tiles30c.Zl",
            [LibraryFile.WemadeMir3_Sand_Tilesc] = @"Data\Map Data\Sand\Tilesc.Zl",
            [LibraryFile.WemadeMir3_Sand_Wallsc] = @"Data\Map Data\Sand\Wallsc.Zl",

            [LibraryFile.WemadeMir3_Snow_Animationsc] = @"Data\Map Data\Snow\Animationsc.Zl",
            [LibraryFile.WemadeMir3_Snow_Cliffsc] = @"Data\Map Data\Snow\Cliffsc.Zl",
            [LibraryFile.WemadeMir3_Snow_Dungeonsc] = @"Data\Map Data\Snow\Dungeonsc.Zl",
            [LibraryFile.WemadeMir3_Snow_Furnituresc] = @"Data\Map Data\Snow\Furnituresc.Zl",
            [LibraryFile.WemadeMir3_Snow_Housesc] = @"Data\Map Data\Snow\Housesc.Zl",
            [LibraryFile.WemadeMir3_Snow_Innersc] = @"Data\Map Data\Snow\Innersc.Zl",
            [LibraryFile.WemadeMir3_Snow_SmObjectsc] = @"Data\Map Data\Snow\SmObjectsc.Zl",
            [LibraryFile.WemadeMir3_Snow_SmTilesc] = @"Data\Map Data\Snow\SmTilesc.Zl",
            [LibraryFile.WemadeMir3_Snow_Tiles5c] = @"Data\Map Data\Snow\Tiles5c.Zl",
            [LibraryFile.WemadeMir3_Snow_Tiles30c] = @"Data\Map Data\Snow\Tiles30c.Zl",
            [LibraryFile.WemadeMir3_Snow_Tilesc] = @"Data\Map Data\Snow\Tilesc.Zl",
            [LibraryFile.WemadeMir3_Snow_Wallsc] = @"Data\Map Data\Snow\Wallsc.Zl",


            [LibraryFile.WemadeMir3_Wood_Animationsc] = @"Data\Map Data\Wood\Animationsc.Zl",
            [LibraryFile.WemadeMir3_Wood_Cliffsc] = @"Data\Map Data\Wood\Cliffsc.Zl",
            [LibraryFile.WemadeMir3_Wood_Dungeonsc] = @"Data\Map Data\Wood\Dungeonsc.Zl",
            [LibraryFile.WemadeMir3_Wood_Furnituresc] = @"Data\Map Data\Wood\Furnituresc.Zl",
            [LibraryFile.WemadeMir3_Wood_Housesc] = @"Data\Map Data\Wood\Housesc.Zl",
            [LibraryFile.WemadeMir3_Wood_Innersc] = @"Data\Map Data\Wood\Innersc.Zl",
            [LibraryFile.WemadeMir3_Wood_SmObjectsc] = @"Data\Map Data\Wood\SmObjectsc.Zl",
            [LibraryFile.WemadeMir3_Wood_SmTilesc] = @"Data\Map Data\Wood\SmTilesc.Zl",
            [LibraryFile.WemadeMir3_Wood_Tiles5c] = @"Data\Map Data\Wood\Tiles5c.Zl",
            [LibraryFile.WemadeMir3_Wood_Tiles30c] = @"Data\Map Data\Wood\Tiles30c.Zl",
            [LibraryFile.WemadeMir3_Wood_Tilesc] = @"Data\Map Data\Wood\Tilesc.Zl",
            [LibraryFile.WemadeMir3_Wood_Wallsc] = @"Data\Map Data\Wood\Wallsc.Zl",

            [LibraryFile.ShandaMir3_Animationsc] = @"Data\Map Data\ShandaMir3\Animationsc.Zl",
            [LibraryFile.ShandaMir3_Cliffsc] = @"Data\Map Data\ShandaMir3\Cliffsc.Zl",
            [LibraryFile.ShandaMir3_Dungeonsc] = @"Data\Map Data\ShandaMir3\Dungeonsc.Zl",
            [LibraryFile.ShandaMir3_Furnituresc] = @"Data\Map Data\ShandaMir3\Furnituresc.Zl",
            [LibraryFile.ShandaMir3_Housesc] = @"Data\Map Data\ShandaMir3\Housesc.Zl",
            [LibraryFile.ShandaMir3_Innersc] = @"Data\Map Data\ShandaMir3\Innersc.Zl",
            [LibraryFile.ShandaMir3_Object1c] = @"Data\Map Data\ShandaMir3\Object1c.Zl",
            [LibraryFile.ShandaMir3_Object2c] = @"Data\Map Data\ShandaMir3\Object2c.Zl",
            [LibraryFile.ShandaMir3_SmObjectsc] = @"Data\Map Data\ShandaMir3\SmObjectsc.Zl",
            [LibraryFile.ShandaMir3_SmTilesc] = @"Data\Map Data\ShandaMir3\SmTilesc.Zl",
            [LibraryFile.ShandaMir3_Tiles5c] = @"Data\Map Data\ShandaMir3\Tiles5c.Zl",
            [LibraryFile.ShandaMir3_Tiles30c] = @"Data\Map Data\ShandaMir3\Tiles30c.Zl",
            [LibraryFile.ShandaMir3_Tilesc] = @"Data\Map Data\ShandaMir3\Tilesc.Zl",
            [LibraryFile.ShandaMir3_Wallsc] = @"Data\Map Data\ShandaMir3\Wallsc.Zl",

            [LibraryFile.ShandaMir3_Forest_Animationsc] = @"Data\Map Data\ShandaMir3\Forest\Animationsc.Zl",
            [LibraryFile.ShandaMir3_Forest_Cliffsc] = @"Data\Map Data\ShandaMir3\Forest\Cliffsc.Zl",
            [LibraryFile.ShandaMir3_Forest_Dungeonsc] = @"Data\Map Data\ShandaMir3\Forest\Dungeonsc.Zl",
            [LibraryFile.ShandaMir3_Forest_Furnituresc] = @"Data\Map Data\ShandaMir3\Forest\Furnituresc.Zl",
            [LibraryFile.ShandaMir3_Forest_Housesc] = @"Data\Map Data\ShandaMir3\Forest\Housesc.Zl",
            [LibraryFile.ShandaMir3_Forest_Innersc] = @"Data\Map Data\ShandaMir3\Forest\Innersc.Zl",
            [LibraryFile.ShandaMir3_Forest_SmObjectsc] = @"Data\Map Data\ShandaMir3\Forest\SmObjectsc.Zl",
            [LibraryFile.ShandaMir3_Forest_SmTilesc] = @"Data\Map Data\ShandaMir3\Forest\SmTilesc.Zl",
            [LibraryFile.ShandaMir3_Forest_Tiles5c] = @"Data\Map Data\ShandaMir3\Forest\Tiles5c.Zl",
            [LibraryFile.ShandaMir3_Forest_Tiles30c] = @"Data\Map Data\ShandaMir3\Forest\Tiles30c.Zl",
            [LibraryFile.ShandaMir3_Forest_Tilesc] = @"Data\Map Data\ShandaMir3\Forest\Tilesc.Zl",
            [LibraryFile.ShandaMir3_Forest_Wallsc] = @"Data\Map Data\ShandaMir3\Forest\Wallsc.Zl",

            [LibraryFile.ShandaMir3_Sand_Animationsc] = @"Data\Map Data\ShandaMir3\Sand\Animationsc.Zl",
            [LibraryFile.ShandaMir3_Sand_Cliffsc] = @"Data\Map Data\ShandaMir3\Sand\Cliffsc.Zl",
            [LibraryFile.ShandaMir3_Sand_Dungeonsc] = @"Data\Map Data\ShandaMir3\Sand\Dungeonsc.Zl",
            [LibraryFile.ShandaMir3_Sand_Furnituresc] = @"Data\Map Data\ShandaMir3\Sand\Furnituresc.Zl",
            [LibraryFile.ShandaMir3_Sand_Housesc] = @"Data\Map Data\ShandaMir3\Sand\Housesc.Zl",
            [LibraryFile.ShandaMir3_Sand_Innersc] = @"Data\Map Data\ShandaMir3\Sand\Innersc.Zl",
            [LibraryFile.ShandaMir3_Sand_SmObjectsc] = @"Data\Map Data\ShandaMir3\Sand\SmObjectsc.Zl",
            [LibraryFile.ShandaMir3_Sand_SmTilesc] = @"Data\Map Data\ShandaMir3\Sand\SmTilesc.Zl",
            [LibraryFile.ShandaMir3_Sand_Tiles5c] = @"Data\Map Data\ShandaMir3\Sand\Tiles5c.Zl",
            [LibraryFile.ShandaMir3_Sand_Tiles30c] = @"Data\Map Data\ShandaMir3\Sand\Tiles30c.Zl",
            [LibraryFile.ShandaMir3_Sand_Tilesc] = @"Data\Map Data\ShandaMir3\Sand\Tilesc.Zl",
            [LibraryFile.ShandaMir3_Sand_Wallsc] = @"Data\Map Data\ShandaMir3\Sand\Wallsc.Zl",

            [LibraryFile.ShandaMir3_Snow_Animationsc] = @"Data\Map Data\ShandaMir3\Snow\Animationsc.Zl",
            [LibraryFile.ShandaMir3_Snow_Cliffsc] = @"Data\Map Data\ShandaMir3\Snow\Cliffsc.Zl",
            [LibraryFile.ShandaMir3_Snow_Dungeonsc] = @"Data\Map Data\ShandaMir3\Snow\Dungeonsc.Zl",
            [LibraryFile.ShandaMir3_Snow_Furnituresc] = @"Data\Map Data\ShandaMir3\Snow\Furnituresc.Zl",
            [LibraryFile.ShandaMir3_Snow_Housesc] = @"Data\Map Data\ShandaMir3\Snow\Housesc.Zl",
            [LibraryFile.ShandaMir3_Snow_Innersc] = @"Data\Map Data\ShandaMir3\Snow\Innersc.Zl",
            [LibraryFile.ShandaMir3_Snow_SmObjectsc] = @"Data\Map Data\ShandaMir3\Snow\SmObjectsc.Zl",
            [LibraryFile.ShandaMir3_Snow_SmTilesc] = @"Data\Map Data\ShandaMir3\Snow\SmTilesc.Zl",
            [LibraryFile.ShandaMir3_Snow_Tiles5c] = @"Data\Map Data\ShandaMir3\Snow\Tiles5c.Zl",
            [LibraryFile.ShandaMir3_Snow_Tiles30c] = @"Data\Map Data\ShandaMir3\Snow\Tiles30c.Zl",
            [LibraryFile.ShandaMir3_Snow_Tilesc] = @"Data\Map Data\ShandaMir3\Snow\Tilesc.Zl",
            [LibraryFile.ShandaMir3_Snow_Wallsc] = @"Data\Map Data\ShandaMir3\Snow\Wallsc.Zl",


            [LibraryFile.ShandaMir3_Wood_Animationsc] = @"Data\Map Data\ShandaMir3\Wood\Animationsc.Zl",
            [LibraryFile.ShandaMir3_Wood_Cliffsc] = @"Data\Map Data\ShandaMir3\Wood\Cliffsc.Zl",
            [LibraryFile.ShandaMir3_Wood_Dungeonsc] = @"Data\Map Data\ShandaMir3\Wood\Dungeonsc.Zl",
            [LibraryFile.ShandaMir3_Wood_Furnituresc] = @"Data\Map Data\ShandaMir3\Wood\Furnituresc.Zl",
            [LibraryFile.ShandaMir3_Wood_Housesc] = @"Data\Map Data\ShandaMir3\Wood\Housesc.Zl",
            [LibraryFile.ShandaMir3_Wood_Innersc] = @"Data\Map Data\ShandaMir3\Wood\Innersc.Zl",
            [LibraryFile.ShandaMir3_Wood_SmObjectsc] = @"Data\Map Data\ShandaMir3\Wood\SmObjectsc.Zl",
            [LibraryFile.ShandaMir3_Wood_SmTilesc] = @"Data\Map Data\ShandaMir3\Wood\SmTilesc.Zl",
            [LibraryFile.ShandaMir3_Wood_Tiles5c] = @"Data\Map Data\ShandaMir3\Wood\Tiles5c.Zl",
            [LibraryFile.ShandaMir3_Wood_Tiles30c] = @"Data\Map Data\ShandaMir3\Wood\Tiles30c.Zl",
            [LibraryFile.ShandaMir3_Wood_Tilesc] = @"Data\Map Data\ShandaMir3\Wood\Tilesc.Zl",
            [LibraryFile.ShandaMir3_Wood_Wallsc] = @"Data\Map Data\ShandaMir3\Wood\Wallsc.Zl",

        };

        public static Dictionary<int, LibraryFile> KROrder = new Dictionary<int, LibraryFile>
        {
            [0] = LibraryFile.WemadeMir2_Tiles,
            [1] = LibraryFile.WemadeMir2_SmTiles,
            [2] = LibraryFile.WemadeMir2_Objects,
            [3] = LibraryFile.WemadeMir2_Objects2,
            [4] = LibraryFile.WemadeMir2_Objects3,
            [5] = LibraryFile.WemadeMir2_Objects4,
            [6] = LibraryFile.WemadeMir2_Objects5,
            [7] = LibraryFile.WemadeMir2_Objects6,
            [8] = LibraryFile.WemadeMir2_Objects7,
            [9] = LibraryFile.WemadeMir2_Objects8,
            [10] = LibraryFile.WemadeMir2_Objects9,
            [11] = LibraryFile.WemadeMir2_Objects10,
            [12] = LibraryFile.WemadeMir2_Objects11,
            [13] = LibraryFile.WemadeMir2_Objects12,
            [14] = LibraryFile.WemadeMir2_Objects13,
            [15] = LibraryFile.WemadeMir2_Objects14,
            [16] = LibraryFile.WemadeMir2_Objects15,
            [17] = LibraryFile.WemadeMir2_Objects16,
            [18] = LibraryFile.WemadeMir2_Objects17,
            [19] = LibraryFile.WemadeMir2_Objects18,
            [20] = LibraryFile.WemadeMir2_Objects19,
            [21] = LibraryFile.WemadeMir2_Objects20,
            [22] = LibraryFile.WemadeMir2_Objects21,
            [23] = LibraryFile.WemadeMir2_Objects22,
            [24] = LibraryFile.WemadeMir2_Objects23,
            [25] = LibraryFile.WemadeMir2_Objects24,
            [26] = LibraryFile.WemadeMir2_Objects25,
            [27] = LibraryFile.WemadeMir2_Objects26,
            [28] = LibraryFile.WemadeMir2_Objects27,
            [29] = LibraryFile.WemadeMir2_Objects28,
            [30] = LibraryFile.WemadeMir2_Objects29,

            [ShandaMir2OffSet + 0] = LibraryFile.ShandaMir2_Tiles,
            [ShandaMir2OffSet + 1] = LibraryFile.ShandaMir2_Tiles2,
            [ShandaMir2OffSet + 2] = LibraryFile.ShandaMir2_Tiles3,
            [ShandaMir2OffSet + 3] = LibraryFile.ShandaMir2_Tiles4,
            [ShandaMir2OffSet + 4] = LibraryFile.ShandaMir2_Tiles5,
            [ShandaMir2OffSet + 5] = LibraryFile.ShandaMir2_Tiles6,
            [ShandaMir2OffSet + 6] = LibraryFile.ShandaMir2_Tiles7,
            [ShandaMir2OffSet + 7] = LibraryFile.ShandaMir2_Tiles8,
            [ShandaMir2OffSet + 8] = LibraryFile.ShandaMir2_Tiles9,
            [ShandaMir2OffSet + 9] = LibraryFile.ShandaMir2_Tiles10,
            [ShandaMir2OffSet + 10] = LibraryFile.ShandaMir2_SmTiles,
            [ShandaMir2OffSet + 11] = LibraryFile.ShandaMir2_SmTiles2,
            [ShandaMir2OffSet + 12] = LibraryFile.ShandaMir2_SmTiles3,
            [ShandaMir2OffSet + 13] = LibraryFile.ShandaMir2_SmTiles4,
            [ShandaMir2OffSet + 14] = LibraryFile.ShandaMir2_SmTiles5,
            [ShandaMir2OffSet + 15] = LibraryFile.ShandaMir2_SmTiles6,
            [ShandaMir2OffSet + 16] = LibraryFile.ShandaMir2_SmTiles7,
            [ShandaMir2OffSet + 17] = LibraryFile.ShandaMir2_SmTiles8,
            [ShandaMir2OffSet + 18] = LibraryFile.ShandaMir2_SmTiles9,
            [ShandaMir2OffSet + 19] = LibraryFile.ShandaMir2_SmTiles10,
            [ShandaMir2OffSet + 20] = LibraryFile.ShandaMir2_Objects,
            [ShandaMir2OffSet + 21] = LibraryFile.ShandaMir2_Objects2,
            [ShandaMir2OffSet + 22] = LibraryFile.ShandaMir2_Objects3,
            [ShandaMir2OffSet + 23] = LibraryFile.ShandaMir2_Objects4,
            [ShandaMir2OffSet + 24] = LibraryFile.ShandaMir2_Objects5,
            [ShandaMir2OffSet + 25] = LibraryFile.ShandaMir2_Objects6,
            [ShandaMir2OffSet + 26] = LibraryFile.ShandaMir2_Objects7,
            [ShandaMir2OffSet + 27] = LibraryFile.ShandaMir2_Objects8,
            [ShandaMir2OffSet + 28] = LibraryFile.ShandaMir2_Objects9,
            [ShandaMir2OffSet + 29] = LibraryFile.ShandaMir2_Objects10,
            [ShandaMir2OffSet + 30] = LibraryFile.ShandaMir2_Objects11,
            [ShandaMir2OffSet + 31] = LibraryFile.ShandaMir2_Objects12,
            [ShandaMir2OffSet + 32] = LibraryFile.ShandaMir2_Objects13,
            [ShandaMir2OffSet + 33] = LibraryFile.ShandaMir2_Objects14,
            [ShandaMir2OffSet + 34] = LibraryFile.ShandaMir2_Objects15,
            [ShandaMir2OffSet + 35] = LibraryFile.ShandaMir2_Objects16,
            [ShandaMir2OffSet + 36] = LibraryFile.ShandaMir2_Objects17,
            [ShandaMir2OffSet + 37] = LibraryFile.ShandaMir2_Objects18,
            [ShandaMir2OffSet + 38] = LibraryFile.ShandaMir2_Objects19,
            [ShandaMir2OffSet + 39] = LibraryFile.ShandaMir2_Objects20,
            [ShandaMir2OffSet + 40] = LibraryFile.ShandaMir2_Objects21,
            [ShandaMir2OffSet + 41] = LibraryFile.ShandaMir2_Objects22,
            [ShandaMir2OffSet + 42] = LibraryFile.ShandaMir2_Objects23,
            [ShandaMir2OffSet + 43] = LibraryFile.ShandaMir2_Objects24,
            [ShandaMir2OffSet + 44] = LibraryFile.ShandaMir2_Objects25,
            [ShandaMir2OffSet + 45] = LibraryFile.ShandaMir2_Objects26,
            [ShandaMir2OffSet + 46] = LibraryFile.ShandaMir2_Objects27,
            [ShandaMir2OffSet + 47] = LibraryFile.ShandaMir2_Objects28,
            [ShandaMir2OffSet + 48] = LibraryFile.ShandaMir2_Objects29,
            [ShandaMir2OffSet + 49] = LibraryFile.ShandaMir2_Objects30,
            [ShandaMir2OffSet + 50] = LibraryFile.ShandaMir2_Objects31,
            [ShandaMir2OffSet + 51] = LibraryFile.ShandaMir2_Objects32,
            [ShandaMir2OffSet + 52] = LibraryFile.ShandaMir2_Objects33,
            [ShandaMir2OffSet + 53] = LibraryFile.ShandaMir2_Objects34,
            [ShandaMir2OffSet + 54] = LibraryFile.ShandaMir2_Objects35,
            [ShandaMir2OffSet + 55] = LibraryFile.ShandaMir2_Objects36,
            [ShandaMir2OffSet + 56] = LibraryFile.ShandaMir2_Objects37,
            [ShandaMir2OffSet + 57] = LibraryFile.ShandaMir2_Objects38,
            [ShandaMir2OffSet + 58] = LibraryFile.ShandaMir2_Objects39,
            [ShandaMir2OffSet + 59] = LibraryFile.ShandaMir2_Objects40,
            [ShandaMir2OffSet + 60] = LibraryFile.ShandaMir2_Objects41,
            [ShandaMir2OffSet + 61] = LibraryFile.ShandaMir2_Objects42,
            [ShandaMir2OffSet + 62] = LibraryFile.ShandaMir2_Objects43,
            [ShandaMir2OffSet + 63] = LibraryFile.ShandaMir2_Objects44,
            [ShandaMir2OffSet + 64] = LibraryFile.ShandaMir2_Objects45,
            [ShandaMir2OffSet + 65] = LibraryFile.ShandaMir2_Objects46,
            [ShandaMir2OffSet + 66] = LibraryFile.ShandaMir2_Objects47,
            [ShandaMir2OffSet + 67] = LibraryFile.ShandaMir2_Objects48,
            [ShandaMir2OffSet + 68] = LibraryFile.ShandaMir2_Objects49,
            [ShandaMir2OffSet + 69] = LibraryFile.ShandaMir2_Objects50,
            [ShandaMir2OffSet + 70] = LibraryFile.ShandaMir2_Objects51,
            [ShandaMir2OffSet + 71] = LibraryFile.ShandaMir2_Objects52,
            [ShandaMir2OffSet + 72] = LibraryFile.ShandaMir2_Objects53,
            [ShandaMir2OffSet + 73] = LibraryFile.ShandaMir2_Objects54,
            [ShandaMir2OffSet + 74] = LibraryFile.ShandaMir2_Objects55,
            [ShandaMir2OffSet + 75] = LibraryFile.ShandaMir2_Objects56,
            [ShandaMir2OffSet + 76] = LibraryFile.ShandaMir2_Objects57,
            [ShandaMir2OffSet + 77] = LibraryFile.ShandaMir2_Objects58,
            [ShandaMir2OffSet + 78] = LibraryFile.ShandaMir2_Objects59,
            [ShandaMir2OffSet + 79] = LibraryFile.ShandaMir2_Objects60,
            [ShandaMir2OffSet + 80] = LibraryFile.ShandaMir2_Objects61,
            [ShandaMir2OffSet + 81] = LibraryFile.ShandaMir2_Objects62,
            [ShandaMir2OffSet + 82] = LibraryFile.ShandaMir2_Objects63,
            [ShandaMir2OffSet + 83] = LibraryFile.ShandaMir2_Objects64,
            [ShandaMir2OffSet + 84] = LibraryFile.ShandaMir2_Objects65,
            [ShandaMir2OffSet + 85] = LibraryFile.ShandaMir2_Objects66,
            [ShandaMir2OffSet + 86] = LibraryFile.ShandaMir2_Objects67,
            [ShandaMir2OffSet + 87] = LibraryFile.ShandaMir2_Objects68,
            [ShandaMir2OffSet + 88] = LibraryFile.ShandaMir2_Objects69,
            [ShandaMir2OffSet + 89] = LibraryFile.ShandaMir2_Objects70,
            [ShandaMir2OffSet + 90] = LibraryFile.ShandaMir2_AniTiles,

            [WemadeMir3OffSet + 0] = LibraryFile.WemadeMir3_Tilesc,
            [WemadeMir3OffSet + 1] = LibraryFile.WemadeMir3_Tiles30c,
            [WemadeMir3OffSet + 2] = LibraryFile.WemadeMir3_Tiles5c,
            [WemadeMir3OffSet + 3] = LibraryFile.WemadeMir3_SmTilesc,
            [WemadeMir3OffSet + 4] = LibraryFile.WemadeMir3_Housesc,
            [WemadeMir3OffSet + 5] = LibraryFile.WemadeMir3_Cliffsc,
            [WemadeMir3OffSet + 6] = LibraryFile.WemadeMir3_Dungeonsc,
            [WemadeMir3OffSet + 7] = LibraryFile.WemadeMir3_Innersc,
            [WemadeMir3OffSet + 8] = LibraryFile.WemadeMir3_Furnituresc,
            [WemadeMir3OffSet + 9] = LibraryFile.WemadeMir3_Wallsc,
            [WemadeMir3OffSet + 10] = LibraryFile.WemadeMir3_SmObjectsc,
            [WemadeMir3OffSet + 11] = LibraryFile.WemadeMir3_Animationsc,
            [WemadeMir3OffSet + 12] = LibraryFile.WemadeMir3_Object1c,
            [WemadeMir3OffSet + 13] = LibraryFile.WemadeMir3_Object2c,


            [WemadeMir3OffSet + 15] = LibraryFile.WemadeMir3_Wood_Tilesc,
            [WemadeMir3OffSet + 16] = LibraryFile.WemadeMir3_Wood_Tiles30c,
            [WemadeMir3OffSet + 17] = LibraryFile.WemadeMir3_Wood_Tiles5c,
            [WemadeMir3OffSet + 18] = LibraryFile.WemadeMir3_Wood_SmTilesc,
            [WemadeMir3OffSet + 19] = LibraryFile.WemadeMir3_Wood_Housesc,
            [WemadeMir3OffSet + 20] = LibraryFile.WemadeMir3_Wood_Cliffsc,
            [WemadeMir3OffSet + 21] = LibraryFile.WemadeMir3_Wood_Dungeonsc,
            [WemadeMir3OffSet + 22] = LibraryFile.WemadeMir3_Wood_Innersc,
            [WemadeMir3OffSet + 23] = LibraryFile.WemadeMir3_Wood_Furnituresc,
            [WemadeMir3OffSet + 24] = LibraryFile.WemadeMir3_Wood_Wallsc,
            [WemadeMir3OffSet + 25] = LibraryFile.WemadeMir3_Wood_SmObjectsc,
            [WemadeMir3OffSet + 26] = LibraryFile.WemadeMir3_Wood_Animationsc,


            [WemadeMir3OffSet + 30] = LibraryFile.WemadeMir3_Sand_Tilesc,
            [WemadeMir3OffSet + 31] = LibraryFile.WemadeMir3_Sand_Tiles30c,
            [WemadeMir3OffSet + 32] = LibraryFile.WemadeMir3_Sand_Tiles5c,
            [WemadeMir3OffSet + 33] = LibraryFile.WemadeMir3_Sand_SmTilesc,
            [WemadeMir3OffSet + 34] = LibraryFile.WemadeMir3_Sand_Housesc,
            [WemadeMir3OffSet + 35] = LibraryFile.WemadeMir3_Sand_Cliffsc,
            [WemadeMir3OffSet + 36] = LibraryFile.WemadeMir3_Sand_Dungeonsc,
            [WemadeMir3OffSet + 37] = LibraryFile.WemadeMir3_Sand_Innersc,
            [WemadeMir3OffSet + 38] = LibraryFile.WemadeMir3_Sand_Furnituresc,
            [WemadeMir3OffSet + 39] = LibraryFile.WemadeMir3_Sand_Wallsc,
            [WemadeMir3OffSet + 40] = LibraryFile.WemadeMir3_Sand_SmObjectsc,
            [WemadeMir3OffSet + 41] = LibraryFile.WemadeMir3_Sand_Animationsc,


            [WemadeMir3OffSet + 45] = LibraryFile.WemadeMir3_Snow_Tilesc,
            [WemadeMir3OffSet + 46] = LibraryFile.WemadeMir3_Snow_Tiles30c,
            [WemadeMir3OffSet + 47] = LibraryFile.WemadeMir3_Snow_Tiles5c,
            [WemadeMir3OffSet + 48] = LibraryFile.WemadeMir3_Snow_SmTilesc,
            [WemadeMir3OffSet + 49] = LibraryFile.WemadeMir3_Snow_Housesc,
            [WemadeMir3OffSet + 50] = LibraryFile.WemadeMir3_Snow_Cliffsc,
            [WemadeMir3OffSet + 51] = LibraryFile.WemadeMir3_Snow_Dungeonsc,
            [WemadeMir3OffSet + 52] = LibraryFile.WemadeMir3_Snow_Innersc,
            [WemadeMir3OffSet + 53] = LibraryFile.WemadeMir3_Snow_Furnituresc,
            [WemadeMir3OffSet + 54] = LibraryFile.WemadeMir3_Snow_Wallsc,
            [WemadeMir3OffSet + 55] = LibraryFile.WemadeMir3_Snow_SmObjectsc,
            [WemadeMir3OffSet + 56] = LibraryFile.WemadeMir3_Snow_Animationsc,


            [WemadeMir3OffSet + 60] = LibraryFile.WemadeMir3_Forest_Tilesc,
            [WemadeMir3OffSet + 61] = LibraryFile.WemadeMir3_Forest_Tiles30c,
            [WemadeMir3OffSet + 62] = LibraryFile.WemadeMir3_Forest_Tiles5c,
            [WemadeMir3OffSet + 63] = LibraryFile.WemadeMir3_Forest_SmTilesc,
            [WemadeMir3OffSet + 64] = LibraryFile.WemadeMir3_Forest_Housesc,
            [WemadeMir3OffSet + 65] = LibraryFile.WemadeMir3_Forest_Cliffsc,
            [WemadeMir3OffSet + 66] = LibraryFile.WemadeMir3_Forest_Dungeonsc,
            [WemadeMir3OffSet + 67] = LibraryFile.WemadeMir3_Forest_Innersc,
            [WemadeMir3OffSet + 68] = LibraryFile.WemadeMir3_Forest_Furnituresc,
            [WemadeMir3OffSet + 69] = LibraryFile.WemadeMir3_Forest_Wallsc,
            [WemadeMir3OffSet + 70] = LibraryFile.WemadeMir3_Forest_SmObjectsc,
            [WemadeMir3OffSet + 71] = LibraryFile.WemadeMir3_Forest_Animationsc,

            [ShandaMir3OffSet + 0] = LibraryFile.ShandaMir3_Tilesc,
            [ShandaMir3OffSet + 1] = LibraryFile.ShandaMir3_Tiles30c,
            [ShandaMir3OffSet + 2] = LibraryFile.ShandaMir3_Tiles5c,
            [ShandaMir3OffSet + 3] = LibraryFile.ShandaMir3_SmTilesc,
            [ShandaMir3OffSet + 4] = LibraryFile.ShandaMir3_Housesc,
            [ShandaMir3OffSet + 5] = LibraryFile.ShandaMir3_Cliffsc,
            [ShandaMir3OffSet + 6] = LibraryFile.ShandaMir3_Dungeonsc,
            [ShandaMir3OffSet + 7] = LibraryFile.ShandaMir3_Innersc,
            [ShandaMir3OffSet + 8] = LibraryFile.ShandaMir3_Furnituresc,
            [ShandaMir3OffSet + 9] = LibraryFile.ShandaMir3_Wallsc,
            [ShandaMir3OffSet + 10] = LibraryFile.ShandaMir3_SmObjectsc,
            [ShandaMir3OffSet + 11] = LibraryFile.ShandaMir3_Animationsc,
            [ShandaMir3OffSet + 12] = LibraryFile.ShandaMir3_Object1c,
            [ShandaMir3OffSet + 13] = LibraryFile.ShandaMir3_Object2c,

            [ShandaMir3OffSet + 15] = LibraryFile.ShandaMir3_Wood_Tilesc,
            [ShandaMir3OffSet + 16] = LibraryFile.ShandaMir3_Wood_Tiles30c,
            [ShandaMir3OffSet + 17] = LibraryFile.ShandaMir3_Wood_Tiles5c,
            [ShandaMir3OffSet + 18] = LibraryFile.ShandaMir3_Wood_SmTilesc,
            [ShandaMir3OffSet + 19] = LibraryFile.ShandaMir3_Wood_Housesc,
            [ShandaMir3OffSet + 20] = LibraryFile.ShandaMir3_Wood_Cliffsc,
            [ShandaMir3OffSet + 21] = LibraryFile.ShandaMir3_Wood_Dungeonsc,
            [ShandaMir3OffSet + 22] = LibraryFile.ShandaMir3_Wood_Innersc,
            [ShandaMir3OffSet + 23] = LibraryFile.ShandaMir3_Wood_Furnituresc,
            [ShandaMir3OffSet + 24] = LibraryFile.ShandaMir3_Wood_Wallsc,
            [ShandaMir3OffSet + 25] = LibraryFile.ShandaMir3_Wood_SmObjectsc,
            [ShandaMir3OffSet + 26] = LibraryFile.ShandaMir3_Wood_Animationsc,

            [ShandaMir3OffSet + 30] = LibraryFile.ShandaMir3_Sand_Tilesc,
            [ShandaMir3OffSet + 31] = LibraryFile.ShandaMir3_Sand_Tiles30c,
            [ShandaMir3OffSet + 32] = LibraryFile.ShandaMir3_Sand_Tiles5c,
            [ShandaMir3OffSet + 33] = LibraryFile.ShandaMir3_Sand_SmTilesc,
            [ShandaMir3OffSet + 34] = LibraryFile.ShandaMir3_Sand_Housesc,
            [ShandaMir3OffSet + 35] = LibraryFile.ShandaMir3_Sand_Cliffsc,
            [ShandaMir3OffSet + 36] = LibraryFile.ShandaMir3_Sand_Dungeonsc,
            [ShandaMir3OffSet + 37] = LibraryFile.ShandaMir3_Sand_Innersc,
            [ShandaMir3OffSet + 38] = LibraryFile.ShandaMir3_Sand_Furnituresc,
            [ShandaMir3OffSet + 39] = LibraryFile.ShandaMir3_Sand_Wallsc,
            [ShandaMir3OffSet + 40] = LibraryFile.ShandaMir3_Sand_SmObjectsc,
            [ShandaMir3OffSet + 41] = LibraryFile.ShandaMir3_Sand_Animationsc,

            [ShandaMir3OffSet + 45] = LibraryFile.ShandaMir3_Snow_Tilesc,
            [ShandaMir3OffSet + 46] = LibraryFile.ShandaMir3_Snow_Tiles30c,
            [ShandaMir3OffSet + 47] = LibraryFile.ShandaMir3_Snow_Tiles5c,
            [ShandaMir3OffSet + 48] = LibraryFile.ShandaMir3_Snow_SmTilesc,
            [ShandaMir3OffSet + 49] = LibraryFile.ShandaMir3_Snow_Housesc,
            [ShandaMir3OffSet + 50] = LibraryFile.ShandaMir3_Snow_Cliffsc,
            [ShandaMir3OffSet + 51] = LibraryFile.ShandaMir3_Snow_Dungeonsc,
            [ShandaMir3OffSet + 52] = LibraryFile.ShandaMir3_Snow_Innersc,
            [ShandaMir3OffSet + 53] = LibraryFile.ShandaMir3_Snow_Furnituresc,
            [ShandaMir3OffSet + 54] = LibraryFile.ShandaMir3_Snow_Wallsc,
            [ShandaMir3OffSet + 55] = LibraryFile.ShandaMir3_Snow_SmObjectsc,
            [ShandaMir3OffSet + 56] = LibraryFile.ShandaMir3_Snow_Animationsc,

            [ShandaMir3OffSet + 60] = LibraryFile.ShandaMir3_Forest_Tilesc,
            [ShandaMir3OffSet + 61] = LibraryFile.ShandaMir3_Forest_Tiles30c,
            [ShandaMir3OffSet + 62] = LibraryFile.ShandaMir3_Forest_Tiles5c,
            [ShandaMir3OffSet + 63] = LibraryFile.ShandaMir3_Forest_SmTilesc,
            [ShandaMir3OffSet + 64] = LibraryFile.ShandaMir3_Forest_Housesc,
            [ShandaMir3OffSet + 65] = LibraryFile.ShandaMir3_Forest_Cliffsc,
            [ShandaMir3OffSet + 66] = LibraryFile.ShandaMir3_Forest_Dungeonsc,
            [ShandaMir3OffSet + 67] = LibraryFile.ShandaMir3_Forest_Innersc,
            [ShandaMir3OffSet + 68] = LibraryFile.ShandaMir3_Forest_Furnituresc,
            [ShandaMir3OffSet + 69] = LibraryFile.ShandaMir3_Forest_Wallsc,
            [ShandaMir3OffSet + 70] = LibraryFile.ShandaMir3_Forest_SmObjectsc,
            [ShandaMir3OffSet + 71] = LibraryFile.ShandaMir3_Forest_Animationsc,
        };
    }

    public enum LibraryFile
    {
        None,

        Interface1c,
        Interface1cExtended,
        Interface,
        GameInter,
        GameInter2,
        Equip,
        EquipEffect_UI,
        EquipEffect_Part,
        EquipEffect_Full,
        EquipEffect_FullEx1,
        EquipEffect_FullEx2,
        EquipEffect_FullEx3,
        ProgUse,
        StoreItems,
        Inventory,
        Ground,
        NPC,
        MiniMap,
        MiniMap2,
        MagicIcon,
        CBIcon,
        QuestIcon,
        MiniGames,
        CastleFlag,
        MiniMapIcon,
        Background,

        NPCImage,
        MonImage,

        PEquipB1,
        PEquipH1,

        M_Hum,
        M_HumEx1,
        M_HumEx2,
        M_HumEx3,
        M_HumEx4,
        M_HumEx10,
        M_HumEx11,
        M_HumEx12,
        M_HumEx13,

        M_HumCx1,

        M_Hair,

        WM_Hum,
        WM_HumEx1,
        WM_HumEx2,
        WM_HumEx3,
        WM_HumEx4,
        WM_HumEx10,
        WM_HumEx11,
        WM_HumEx12,
        WM_HumEx13,

        WM_HumCx1,

        WM_Hair,

        M_HumA,
        M_HumAEx1,
        M_HumAEx2,
        M_HumAEx3,

        M_HumACx1,

        M_HairA,

        WM_HumA,
        WM_HumAEx1,
        WM_HumAEx2,
        WM_HumAEx3,

        WM_HumACx1,

        WM_HairA,


        M_Costume,
        M_CostumeA,
        M_CostumeEx1,

        WM_Costume,
        WM_CostumeA,
        WM_CostumeEx1,

        Horse,
        HorseS,

        HorseIron,
        HorseSilver,
        HorseGold,
        HorseBlue,
        HorseDark,
        HorseDarkEffect,
        HorseRoyal,
        HorseRoyalEffect,
        HorseBlueDragon,
        HorseBlueDragonEffect,

        M_Weapon1,
        M_Weapon2,
        M_Weapon3,
        M_Weapon4,
        M_Weapon5,
        M_Weapon6,
        M_Weapon7,
        M_Weapon10,
        M_Weapon11,
        M_Weapon12,
        M_Weapon13,
        M_Weapon14,
        M_Weapon15,
        M_Weapon16,

        WM_Weapon1,
        WM_Weapon2,
        WM_Weapon3,
        WM_Weapon4,
        WM_Weapon5,
        WM_Weapon6,
        WM_Weapon7,
        WM_Weapon10,
        WM_Weapon11,
        WM_Weapon12,
        WM_Weapon13,
        WM_Weapon14,
        WM_Weapon15,
        WM_Weapon16,

        M_WeaponADL1,
        M_WeaponADL2,
        M_WeaponADL6,
        M_WeaponADR1,
        M_WeaponADR2,
        M_WeaponADR6,

        M_WeaponAOH1,
        M_WeaponAOH2,
        M_WeaponAOH3,
        M_WeaponAOH4,
        M_WeaponAOH5,
        M_WeaponAOH6,

        WM_WeaponADL1,
        WM_WeaponADL2,
        WM_WeaponADL6,
        WM_WeaponADR1,
        WM_WeaponADR2,
        WM_WeaponADR6,

        WM_WeaponAOH1,
        WM_WeaponAOH2,
        WM_WeaponAOH3,
        WM_WeaponAOH4,
        WM_WeaponAOH5,
        WM_WeaponAOH6,

        M_Shield1,
        M_Shield2,

        WM_Shield1,
        WM_Shield2,

        M_Helmet1,
        M_Helmet2,
        M_Helmet3,
        M_Helmet4,
        M_Helmet5,

        M_Helmet11,
        M_Helmet12,
        M_Helmet13,
        M_Helmet14,

        M_HelmetCx1,

        WM_Helmet1,
        WM_Helmet2,
        WM_Helmet3,
        WM_Helmet4,
        WM_Helmet5,

        WM_Helmet11,
        WM_Helmet12,
        WM_Helmet13,
        WM_Helmet14,

        WM_HelmetCx1,

        M_HelmetA1,
        M_HelmetA2,
        M_HelmetA3,
        M_HelmetA4,

        M_HelmetACx1,

        WM_HelmetA1,
        WM_HelmetA2,
        WM_HelmetA3,
        WM_HelmetA4,

        WM_HelmetACx1,

        MonMagic,
        MonMagicEx,
        MonMagicEx2,
        MonMagicEx3,
        MonMagicEx4,
        MonMagicEx5,
        MonMagicEx6,
        MonMagicEx7,
        MonMagicEx8,
        MonMagicEx9,
        MonMagicEx19,
        MonMagicEx20,
        MonMagicEx21,
        MonMagicEx22,
        MonMagicEx23,
        MonMagicEx26,

        Mon_1,
        Mon_2,
        Mon_3,
        Mon_4,
        Mon_5,
        Mon_6,
        Mon_7,
        Mon_8,
        Mon_9,
        Mon_10,

        Mon_11,
        Mon_12,
        Mon_13,
        Mon_14,
        Mon_15,
        Mon_16,
        Mon_17,
        Mon_18,
        Mon_19,
        Mon_20,

        Mon_21,
        Mon_22,
        Mon_23,
        Mon_24,
        Mon_25,
        Mon_26,
        Mon_27,
        Mon_28,
        Mon_29,
        Mon_30,

        Mon_31,
        Mon_32,
        Mon_33,
        Mon_34,
        Mon_35,
        Mon_36,
        Mon_37,
        Mon_38,
        Mon_39,
        Mon_40,

        Mon_41,
        Mon_42,
        Mon_43,
        Mon_44,
        Mon_45,
        Mon_46,
        Mon_47,
        Mon_48,
        Mon_49,
        Mon_50,

        Mon_51,
        Mon_52,
        Mon_53,
        Mon_54,
        Mon_55,
        Mon_56,
        Mon_57,

        Magic,
        MagicEx,
        MagicEx2,
        MagicEx3,
        MagicEx4,
        MagicEx5,
        MagicEx6,
        MagicEx7,
        MagicEx8,
        MagicEx9,
        MagicEx10,
        MagicEx11,

        WemadeMir2_Tiles,
        WemadeMir2_SmTiles,
        WemadeMir2_Objects,
        WemadeMir2_Objects2,
        WemadeMir2_Objects3,
        WemadeMir2_Objects4,
        WemadeMir2_Objects5,
        WemadeMir2_Objects6,
        WemadeMir2_Objects7,
        WemadeMir2_Objects8,
        WemadeMir2_Objects9,
        WemadeMir2_Objects10,
        WemadeMir2_Objects11,
        WemadeMir2_Objects12,
        WemadeMir2_Objects13,
        WemadeMir2_Objects14,
        WemadeMir2_Objects15,
        WemadeMir2_Objects16,
        WemadeMir2_Objects17,
        WemadeMir2_Objects18,
        WemadeMir2_Objects19,
        WemadeMir2_Objects20,
        WemadeMir2_Objects21,
        WemadeMir2_Objects22,
        WemadeMir2_Objects23,
        WemadeMir2_Objects24,
        WemadeMir2_Objects25,
        WemadeMir2_Objects26,
        WemadeMir2_Objects27,
        WemadeMir2_Objects28,
        WemadeMir2_Objects29,
        WemadeMir2_Objects30,

        ShandaMir2_Tiles,
        ShandaMir2_Tiles2,
        ShandaMir2_Tiles3,
        ShandaMir2_Tiles4,
        ShandaMir2_Tiles5,
        ShandaMir2_Tiles6,
        ShandaMir2_Tiles7,
        ShandaMir2_Tiles8,
        ShandaMir2_Tiles9,
        ShandaMir2_Tiles10,
        ShandaMir2_SmTiles,
        ShandaMir2_SmTiles2,
        ShandaMir2_SmTiles3,
        ShandaMir2_SmTiles4,
        ShandaMir2_SmTiles5,
        ShandaMir2_SmTiles6,
        ShandaMir2_SmTiles7,
        ShandaMir2_SmTiles8,
        ShandaMir2_SmTiles9,
        ShandaMir2_SmTiles10,
        ShandaMir2_AniTiles,
        ShandaMir2_Objects,
        ShandaMir2_Objects2,
        ShandaMir2_Objects3,
        ShandaMir2_Objects4,
        ShandaMir2_Objects5,
        ShandaMir2_Objects6,
        ShandaMir2_Objects7,
        ShandaMir2_Objects8,
        ShandaMir2_Objects9,
        ShandaMir2_Objects10,
        ShandaMir2_Objects11,
        ShandaMir2_Objects12,
        ShandaMir2_Objects13,
        ShandaMir2_Objects14,
        ShandaMir2_Objects15,
        ShandaMir2_Objects16,
        ShandaMir2_Objects17,
        ShandaMir2_Objects18,
        ShandaMir2_Objects19,
        ShandaMir2_Objects20,
        ShandaMir2_Objects21,
        ShandaMir2_Objects22,
        ShandaMir2_Objects23,
        ShandaMir2_Objects24,
        ShandaMir2_Objects25,
        ShandaMir2_Objects26,
        ShandaMir2_Objects27,
        ShandaMir2_Objects28,
        ShandaMir2_Objects29,
        ShandaMir2_Objects30,
        ShandaMir2_Objects31,
        ShandaMir2_Objects32,
        ShandaMir2_Objects33,
        ShandaMir2_Objects34,
        ShandaMir2_Objects35,
        ShandaMir2_Objects36,
        ShandaMir2_Objects37,
        ShandaMir2_Objects38,
        ShandaMir2_Objects39,
        ShandaMir2_Objects40,
        ShandaMir2_Objects41,
        ShandaMir2_Objects42,
        ShandaMir2_Objects43,
        ShandaMir2_Objects44,
        ShandaMir2_Objects45,
        ShandaMir2_Objects46,
        ShandaMir2_Objects47,
        ShandaMir2_Objects48,
        ShandaMir2_Objects49,
        ShandaMir2_Objects50,
        ShandaMir2_Objects51,
        ShandaMir2_Objects52,
        ShandaMir2_Objects53,
        ShandaMir2_Objects54,
        ShandaMir2_Objects55,
        ShandaMir2_Objects56,
        ShandaMir2_Objects57,
        ShandaMir2_Objects58,
        ShandaMir2_Objects59,
        ShandaMir2_Objects60,
        ShandaMir2_Objects61,
        ShandaMir2_Objects62,
        ShandaMir2_Objects63,
        ShandaMir2_Objects64,
        ShandaMir2_Objects65,
        ShandaMir2_Objects66,
        ShandaMir2_Objects67,
        ShandaMir2_Objects68,
        ShandaMir2_Objects69,
        ShandaMir2_Objects70,
        ShandaMir2_Objects71,
        ShandaMir2_Objects72,
        ShandaMir2_Objects73,
        ShandaMir2_Objects74,
        ShandaMir2_Objects75,
        ShandaMir2_Objects76,
        ShandaMir2_Objects77,
        ShandaMir2_Objects78,
        ShandaMir2_Objects79,
        ShandaMir2_Objects80,
        ShandaMir2_Objects81,
        ShandaMir2_Objects82,
        ShandaMir2_Objects83,
        ShandaMir2_Objects84,
        ShandaMir2_Objects85,
        ShandaMir2_Objects86,
        ShandaMir2_Objects87,
        ShandaMir2_Objects88,
        ShandaMir2_Objects89,
        ShandaMir2_Objects90,
        ShandaMir2_Objects91,
        ShandaMir2_Objects92,
        ShandaMir2_Objects93,
        ShandaMir2_Objects94,

        WemadeMir3_Animationsc,
        WemadeMir3_Cliffsc,
        WemadeMir3_Dungeonsc,
        WemadeMir3_Furnituresc,
        WemadeMir3_Housesc,
        WemadeMir3_Innersc,
        WemadeMir3_Object1c,
        WemadeMir3_Object2c,
        WemadeMir3_SmObjectsc,
        WemadeMir3_SmTilesc,
        WemadeMir3_Tiles5c,
        WemadeMir3_Tiles30c,
        WemadeMir3_Tilesc,
        WemadeMir3_Wallsc,

        WemadeMir3_Forest_Animationsc,
        WemadeMir3_Forest_Cliffsc,
        WemadeMir3_Forest_Dungeonsc,
        WemadeMir3_Forest_Furnituresc,
        WemadeMir3_Forest_Housesc,
        WemadeMir3_Forest_Innersc,
        WemadeMir3_Forest_SmObjectsc,
        WemadeMir3_Forest_SmTilesc,
        WemadeMir3_Forest_Tiles5c,
        WemadeMir3_Forest_Tiles30c,
        WemadeMir3_Forest_Tilesc,
        WemadeMir3_Forest_Wallsc,

        WemadeMir3_Sand_Animationsc,
        WemadeMir3_Sand_Cliffsc,
        WemadeMir3_Sand_Dungeonsc,
        WemadeMir3_Sand_Furnituresc,
        WemadeMir3_Sand_Housesc,
        WemadeMir3_Sand_Innersc,
        WemadeMir3_Sand_SmObjectsc,
        WemadeMir3_Sand_SmTilesc,
        WemadeMir3_Sand_Tiles5c,
        WemadeMir3_Sand_Tiles30c,
        WemadeMir3_Sand_Tilesc,
        WemadeMir3_Sand_Wallsc,

        WemadeMir3_Snow_Animationsc,
        WemadeMir3_Snow_Cliffsc,
        WemadeMir3_Snow_Dungeonsc,
        WemadeMir3_Snow_Furnituresc,
        WemadeMir3_Snow_Housesc,
        WemadeMir3_Snow_Innersc,
        WemadeMir3_Snow_SmObjectsc,
        WemadeMir3_Snow_SmTilesc,
        WemadeMir3_Snow_Tiles5c,
        WemadeMir3_Snow_Tiles30c,
        WemadeMir3_Snow_Tilesc,
        WemadeMir3_Snow_Wallsc,

        WemadeMir3_Wood_Animationsc,
        WemadeMir3_Wood_Cliffsc,
        WemadeMir3_Wood_Dungeonsc,
        WemadeMir3_Wood_Furnituresc,
        WemadeMir3_Wood_Housesc,
        WemadeMir3_Wood_Innersc,
        WemadeMir3_Wood_SmObjectsc,
        WemadeMir3_Wood_SmTilesc,
        WemadeMir3_Wood_Tiles5c,
        WemadeMir3_Wood_Tiles30c,
        WemadeMir3_Wood_Tilesc,
        WemadeMir3_Wood_Wallsc,

        ShandaMir3_Animationsc,
        ShandaMir3_Cliffsc,
        ShandaMir3_Dungeonsc,
        ShandaMir3_Furnituresc,
        ShandaMir3_Housesc,
        ShandaMir3_Innersc,
        ShandaMir3_Object1c,
        ShandaMir3_Object2c,
        ShandaMir3_SmObjectsc,
        ShandaMir3_SmTilesc,
        ShandaMir3_Tiles5c,
        ShandaMir3_Tiles30c,
        ShandaMir3_Tilesc,
        ShandaMir3_Wallsc,

        ShandaMir3_Forest_Animationsc,
        ShandaMir3_Forest_Cliffsc,
        ShandaMir3_Forest_Dungeonsc,
        ShandaMir3_Forest_Furnituresc,
        ShandaMir3_Forest_Housesc,
        ShandaMir3_Forest_Innersc,
        ShandaMir3_Forest_SmObjectsc,
        ShandaMir3_Forest_SmTilesc,
        ShandaMir3_Forest_Tiles5c,
        ShandaMir3_Forest_Tiles30c,
        ShandaMir3_Forest_Tilesc,
        ShandaMir3_Forest_Wallsc,

        ShandaMir3_Sand_Animationsc,
        ShandaMir3_Sand_Cliffsc,
        ShandaMir3_Sand_Dungeonsc,
        ShandaMir3_Sand_Furnituresc,
        ShandaMir3_Sand_Housesc,
        ShandaMir3_Sand_Innersc,
        ShandaMir3_Sand_SmObjectsc,
        ShandaMir3_Sand_SmTilesc,
        ShandaMir3_Sand_Tiles5c,
        ShandaMir3_Sand_Tiles30c,
        ShandaMir3_Sand_Tilesc,
        ShandaMir3_Sand_Wallsc,

        ShandaMir3_Snow_Animationsc,
        ShandaMir3_Snow_Cliffsc,
        ShandaMir3_Snow_Dungeonsc,
        ShandaMir3_Snow_Furnituresc,
        ShandaMir3_Snow_Housesc,
        ShandaMir3_Snow_Innersc,
        ShandaMir3_Snow_SmObjectsc,
        ShandaMir3_Snow_SmTilesc,
        ShandaMir3_Snow_Tiles5c,
        ShandaMir3_Snow_Tiles30c,
        ShandaMir3_Snow_Tilesc,
        ShandaMir3_Snow_Wallsc,

        ShandaMir3_Wood_Animationsc,
        ShandaMir3_Wood_Cliffsc,
        ShandaMir3_Wood_Dungeonsc,
        ShandaMir3_Wood_Furnituresc,
        ShandaMir3_Wood_Housesc,
        ShandaMir3_Wood_Innersc,
        ShandaMir3_Wood_SmObjectsc,
        ShandaMir3_Wood_SmTilesc,
        ShandaMir3_Wood_Tiles5c,
        ShandaMir3_Wood_Tiles30c,
        ShandaMir3_Wood_Tilesc,
        ShandaMir3_Wood_Wallsc,
    }
}
